package SPDX.Licenses is

   pragma Style_Checks (Off); --  Genrated code

   Version : constant String :="3.24.0";

   type Id is (
               Id_0BSD,
               Id_3D_Slicer_1_0,
               AAL,
               AdaCore_doc,
               ADSL,
               AFL_1_1,
               AFL_1_2,
               AFL_2_0,
               AFL_2_1,
               AFL_3_0,
               AGPL_1_0_only,
               AGPL_1_0_or_later,
               AGPL_3_0_only,
               AGPL_3_0_or_later,
               AMD_newlib,
               AMDPLPA,
               AML,
               AML_glslang,
               AMPAS,
               ANTLR_PD,
               ANTLR_PD_fallback,
               any_OSI,
               APAFML,
               APL_1_0,
               APSL_1_0,
               APSL_1_1,
               APSL_1_2,
               APSL_2_0,
               App_s2p,
               Abstyles,
               Adobe_2006,
               Adobe_Display_PostScript,
               Adobe_Glyph,
               Adobe_Utopia,
               Afmparse,
               Aladdin,
               Apache_1_0,
               Apache_1_1,
               Apache_2_0,
               Arphic_1999,
               Artistic_1_0,
               Artistic_1_0_Perl,
               Artistic_1_0_cl8,
               Artistic_2_0,
               ASWF_Digital_Assets_1_0,
               ASWF_Digital_Assets_1_1,
               Baekmuk,
               bcrypt_Solar_Designer,
               Bitstream_Charter,
               Bitstream_Vera,
               Boehm_GC,
               Brian_Gladman_2_Clause,
               Brian_Gladman_3_Clause,
               BSD_1_Clause,
               BSD_2_Clause,
               BSD_2_Clause_Darwin,
               BSD_2_Clause_first_lines,
               BSD_2_Clause_Patent,
               BSD_2_Clause_Views,
               BSD_3_Clause,
               BSD_3_Clause_acpica,
               BSD_3_Clause_Attribution,
               BSD_3_Clause_Clear,
               BSD_3_Clause_flex,
               BSD_3_Clause_HP,
               BSD_3_Clause_LBNL,
               BSD_3_Clause_Modification,
               BSD_3_Clause_No_Military_License,
               BSD_3_Clause_No_Nuclear_License,
               BSD_3_Clause_No_Nuclear_License_2014,
               BSD_3_Clause_No_Nuclear_Warranty,
               BSD_3_Clause_Open_MPI,
               BSD_3_Clause_Sun,
               BSD_4_Clause,
               BSD_4_Clause_Shortened,
               BSD_4_Clause_UC,
               BSD_4_3RENO,
               BSD_4_3TAHOE,
               BSD_Advertising_Acknowledgement,
               BSD_Attribution_HPND_disclaimer,
               BSD_Inferno_Nettverk,
               BSD_Protection,
               BSD_Source_beginning_file,
               BSD_Source_Code,
               BSD_Systemics,
               BSD_Systemics_W3Works,
               BSL_1_0,
               Bahyph,
               Barr,
               Beerware,
               BitTorrent_1_0,
               BitTorrent_1_1,
               BlueOak_1_0_0,
               Borceux,
               BUSL_1_1,
               C_UDA_1_0,
               CAL_1_0,
               CAL_1_0_Combined_Work_Exception,
               Catharon,
               CATOSL_1_1,
               CC_BY_1_0,
               CC_BY_2_0,
               CC_BY_2_5,
               CC_BY_2_5_AU,
               CC_BY_3_0,
               CC_BY_3_0_AT,
               CC_BY_3_0_AU,
               CC_BY_3_0_DE,
               CC_BY_3_0_IGO,
               CC_BY_3_0_NL,
               CC_BY_3_0_US,
               CC_BY_4_0,
               CC_BY_NC_1_0,
               CC_BY_NC_2_0,
               CC_BY_NC_2_5,
               CC_BY_NC_3_0,
               CC_BY_NC_3_0_DE,
               CC_BY_NC_4_0,
               CC_BY_NC_ND_1_0,
               CC_BY_NC_ND_2_0,
               CC_BY_NC_ND_2_5,
               CC_BY_NC_ND_3_0,
               CC_BY_NC_ND_3_0_DE,
               CC_BY_NC_ND_3_0_IGO,
               CC_BY_NC_ND_4_0,
               CC_BY_NC_SA_1_0,
               CC_BY_NC_SA_2_0,
               CC_BY_NC_SA_2_0_DE,
               CC_BY_NC_SA_2_0_FR,
               CC_BY_NC_SA_2_0_UK,
               CC_BY_NC_SA_2_5,
               CC_BY_NC_SA_3_0,
               CC_BY_NC_SA_3_0_DE,
               CC_BY_NC_SA_3_0_IGO,
               CC_BY_NC_SA_4_0,
               CC_BY_ND_1_0,
               CC_BY_ND_2_0,
               CC_BY_ND_2_5,
               CC_BY_ND_3_0,
               CC_BY_ND_3_0_DE,
               CC_BY_ND_4_0,
               CC_BY_SA_1_0,
               CC_BY_SA_2_0,
               CC_BY_SA_2_0_UK,
               CC_BY_SA_2_1_JP,
               CC_BY_SA_2_5,
               CC_BY_SA_3_0,
               CC_BY_SA_3_0_AT,
               CC_BY_SA_3_0_DE,
               CC_BY_SA_3_0_IGO,
               CC_BY_SA_4_0,
               CC_PDDC,
               CC0_1_0,
               CDDL_1_0,
               CDDL_1_1,
               CDL_1_0,
               CDLA_Permissive_1_0,
               CDLA_Permissive_2_0,
               CDLA_Sharing_1_0,
               CECILL_1_0,
               CECILL_1_1,
               CECILL_2_0,
               CECILL_2_1,
               CECILL_B,
               CECILL_C,
               CERN_OHL_1_1,
               CERN_OHL_1_2,
               CERN_OHL_P_2_0,
               CERN_OHL_S_2_0,
               CERN_OHL_W_2_0,
               CFITSIO,
               check_cvs,
               checkmk,
               Clips,
               CMU_Mach,
               CMU_Mach_nodoc,
               CNRI_Jython,
               CNRI_Python,
               CNRI_Python_GPL_Compatible,
               COIL_1_0,
               Community_Spec_1_0,
               Cornell_Lossless_JPEG,
               CPAL_1_0,
               CPL_1_0,
               CPOL_1_02,
               CUA_OPL_1_0,
               Caldera,
               Caldera_no_preamble,
               ClArtistic,
               Condor_1_1,
               Cronyx,
               Crossword,
               CrystalStacker,
               Cube,
               cve_tou,
               D_FSL_1_0,
               DEC_3_Clause,
               DL_DE_BY_2_0,
               DL_DE_ZERO_2_0,
               DOC,
               DSDP,
               Dotseqn,
               DRL_1_0,
               DRL_1_1,
               dtoa,
               ECL_1_0,
               ECL_2_0,
               EFL_1_0,
               EFL_2_0,
               Elastic_2_0,
               EPICS,
               EPL_1_0,
               EPL_2_0,
               EUDatagrid,
               EUPL_1_0,
               EUPL_1_1,
               EUPL_1_2,
               Entessa,
               ErlPL_1_1,
               Eurosym,
               FBM,
               FDK_AAC,
               Ferguson_Twofish,
               FreeBSD_DOC,
               FSFAP,
               FSFAP_no_warranty_disclaimer,
               FSFUL,
               FSFULLR,
               FSFULLRWD,
               FTL,
               Fair,
               Frameworx_1_0,
               FreeImage,
               Furuseth,
               fwlw,
               GCR_docs,
               GD,
               GFDL_1_1_invariants_only,
               GFDL_1_1_invariants_or_later,
               GFDL_1_1_no_invariants_only,
               GFDL_1_1_no_invariants_or_later,
               GFDL_1_1_only,
               GFDL_1_1_or_later,
               GFDL_1_2_invariants_only,
               GFDL_1_2_invariants_or_later,
               GFDL_1_2_no_invariants_only,
               GFDL_1_2_no_invariants_or_later,
               GFDL_1_2_only,
               GFDL_1_2_or_later,
               GFDL_1_3_invariants_only,
               GFDL_1_3_invariants_or_later,
               GFDL_1_3_no_invariants_only,
               GFDL_1_3_no_invariants_or_later,
               GFDL_1_3_only,
               GFDL_1_3_or_later,
               GL2PS,
               GLWTPL,
               GPL_1_0_only,
               GPL_1_0_or_later,
               GPL_2_0_only,
               GPL_2_0_or_later,
               GPL_3_0_only,
               GPL_3_0_or_later,
               Giftware,
               Glide,
               Glulxe,
               HPND,
               HPND_DEC,
               HPND_doc,
               HPND_doc_sell,
               HPND_export_US,
               HPND_export_US_acknowledgement,
               HPND_export_US_modify,
               HPND_export2_US,
               HPND_Fenneberg_Livingston,
               HPND_INRIA_IMAG,
               HPND_Intel,
               HPND_Kevlin_Henney,
               HPND_Markus_Kuhn,
               HPND_merchantability_variant,
               HPND_MIT_disclaimer,
               HPND_Pbmplus,
               HPND_sell_MIT_disclaimer_xserver,
               HPND_sell_regexpr,
               HPND_sell_variant,
               HPND_sell_variant_MIT_disclaimer,
               HPND_sell_variant_MIT_disclaimer_rev,
               HPND_UC,
               HPND_UC_export_US,
               Graphics_Gems,
               gtkbook,
               Gutmann,
               HaskellReport,
               hdparm,
               Hippocratic_2_1,
               HP_1986,
               HP_1989,
               HTMLTIDY,
               IBM_pibs,
               ICU,
               IEC_Code_Components_EULA,
               IJG,
               IJG_short,
               IPA,
               IPL_1_0,
               ISC,
               ISC_Veillard,
               ImageMagick,
               Imlib2,
               Info_ZIP,
               Inner_Net_2_0,
               Intel,
               Intel_ACPI,
               Interbase_1_0,
               Jam,
               JPL_image,
               JPNIC,
               JSON,
               JasPer_2_0,
               Kastrup,
               Kazlib,
               Knuth_CTAN,
               LAL_1_2,
               LAL_1_3,
               LGPL_2_0_only,
               LGPL_2_0_or_later,
               LGPL_2_1_only,
               LGPL_2_1_or_later,
               LGPL_3_0_only,
               LGPL_3_0_or_later,
               LGPLLR,
               libutil_David_Nugent,
               Id_LOOP,
               LPD_document,
               LPL_1_0,
               LPL_1_02,
               LPPL_1_0,
               LPPL_1_1,
               LPPL_1_2,
               LPPL_1_3a,
               LPPL_1_3c,
               Latex2e,
               Latex2e_translated_notice,
               Leptonica,
               LiLiQ_P_1_1,
               LiLiQ_R_1_1,
               LiLiQ_Rplus_1_1,
               Libpng,
               Linux_man_pages_1_para,
               Linux_man_pages_copyleft,
               Linux_man_pages_copyleft_2_para,
               Linux_man_pages_copyleft_var,
               Linux_OpenIB,
               lsof,
               Lucida_Bitmap_Fonts,
               LZMA_SDK_9_11_to_9_20,
               LZMA_SDK_9_22,
               Mackerras_3_Clause,
               Mackerras_3_Clause_acknowledgment,
               magaz,
               mailprio,
               Martin_Birgmeier,
               McPhee_slideshow,
               metamail,
               Minpack,
               MIT,
               MIT_0,
               MIT_CMU,
               MIT_advertising,
               MIT_enna,
               MIT_feh,
               MIT_Festival,
               MIT_Khronos_old,
               MIT_Modern_Variant,
               MIT_open_group,
               MIT_testregex,
               MIT_Wu,
               MITNFA,
               MMIXware,
               MPEG_SSG,
               mpi_permissive,
               MPL_1_0,
               MPL_1_1,
               MPL_2_0,
               MPL_2_0_no_copyleft_exception,
               mplus,
               MS_LPL,
               MS_PL,
               MS_RL,
               MTLL,
               MakeIndex,
               MirOS,
               Motosoto,
               MulanPSL_1_0,
               MulanPSL_2_0,
               Multics,
               Mup,
               NAIST_2003,
               NASA_1_3,
               NBPL_1_0,
               NCBI_PD,
               NCGL_UK_2_0,
               NCL,
               NCSA,
               NGPL,
               NICTA_1_0,
               NIST_PD,
               NIST_PD_fallback,
               NIST_Software,
               NLOD_1_0,
               NLOD_2_0,
               NLPL,
               NOSL,
               NPL_1_0,
               NPL_1_1,
               NPOSL_3_0,
               NRL,
               NTP,
               NTP_0,
               Naumen,
               Net_SNMP,
               NetCDF,
               Newsletr,
               Nokia,
               Noweb,
               O_UDA_1_0,
               OAR,
               OCCT_PL,
               OCLC_2_0,
               ODC_By_1_0,
               ODbL_1_0,
               OFFIS,
               OFL_1_0,
               OFL_1_0_RFN,
               OFL_1_0_no_RFN,
               OFL_1_1,
               OFL_1_1_RFN,
               OFL_1_1_no_RFN,
               OGC_1_0,
               OGDL_Taiwan_1_0,
               OGL_Canada_2_0,
               OGL_UK_1_0,
               OGL_UK_2_0,
               OGL_UK_3_0,
               OGTSL,
               OLDAP_1_1,
               OLDAP_1_2,
               OLDAP_1_3,
               OLDAP_1_4,
               OLDAP_2_0,
               OLDAP_2_0_1,
               OLDAP_2_1,
               OLDAP_2_2,
               OLDAP_2_2_1,
               OLDAP_2_2_2,
               OLDAP_2_3,
               OLDAP_2_4,
               OLDAP_2_5,
               OLDAP_2_6,
               OLDAP_2_7,
               OLDAP_2_8,
               OLFL_1_3,
               OML,
               OpenPBS_2_3,
               OpenVision,
               OPL_1_0,
               OPL_UK_3_0,
               OPUBL_1_0,
               OSET_PL_2_1,
               OSL_1_0,
               OSL_1_1,
               OSL_2_0,
               OSL_2_1,
               OSL_3_0,
               OpenSSL,
               OpenSSL_standalone,
               PADL,
               PDDL_1_0,
               PHP_3_0,
               PHP_3_01,
               PSF_2_0,
               Pixar,
               pkgconf,
               Parity_6_0_0,
               Parity_7_0_0,
               Plexus,
               pnmstitch,
               PolyForm_Noncommercial_1_0_0,
               PolyForm_Small_Business_1_0_0,
               PostgreSQL,
               PPL,
               Python_2_0,
               QPL_1_0,
               QPL_1_0_INRIA_2004,
               Python_2_0_1,
               python_ldap,
               Qhull,
               radvd,
               RHeCos_1_1,
               RPL_1_1,
               RPL_1_5,
               RPSL_1_0,
               RSA_MD,
               RSCPL,
               Rdisc,
               Ruby,
               SAX_PD,
               SAX_PD_2_0,
               SCEA,
               SchemeReport,
               SGI_B_1_0,
               SGI_B_1_1,
               SGI_B_2_0,
               SGI_OpenGL,
               SGP4,
               SHL_0_5,
               SHL_0_51,
               SISSL,
               SISSL_1_2,
               SL,
               SMLNJ,
               SMPPL,
               SNIA,
               snprintf,
               softSurfer,
               Soundex,
               SPL_1_0,
               ssh_keyscan,
               SSH_OpenSSH,
               SSH_short,
               SSLeay_standalone,
               SSPL_1_0,
               SWL,
               Saxpath,
               Sendmail,
               Sendmail_8_23,
               SimPL_2_0,
               Sleepycat,
               Spencer_86,
               Spencer_94,
               Spencer_99,
               SugarCRM_1_1_3,
               Sun_PPP,
               Sun_PPP_2000,
               SunPro,
               swrule,
               Symlinks,
               TAPR_OHL_1_0,
               TCL,
               TCP_wrappers,
               TermReadKey,
               TGPPL_1_0,
               threeparttable,
               TMate,
               TORQUE_1_1,
               TOSL,
               TPDL,
               TPL_1_0,
               TTWL,
               TTYP0,
               TU_Berlin_1_0,
               TU_Berlin_2_0,
               UCAR,
               UCL_1_0,
               UPL_1_0,
               ulem,
               UMich_Merit,
               Unicode_3_0,
               Unicode_DFS_2015,
               Unicode_DFS_2016,
               Unicode_TOU,
               UnixCrypt,
               Unlicense,
               URT_RLE,
               VOSTROM,
               VSL_1_0,
               Vim,
               W3C,
               W3C_19980720,
               W3C_20150513,
               w3m,
               WTFPL,
               Watcom_1_0,
               Widget_Workshop,
               Wsuipa,
               X11,
               XFree86_1_1,
               XSkat,
               X11_distribute_modifications_variant,
               Xdebug_1_03,
               Xerox,
               Xfig,
               xkeyboard_config_Zinoviev,
               xlock,
               Xnet,
               xzoom,
               YPL_1_0,
               YPL_1_1,
               ZPL_1_1,
               ZPL_2_0,
               ZPL_2_1,
               Zed,
               Zeeff,
               Zend_2_0,
               Zimbra_1_3,
               Zimbra_1_4,
               Zlib,
               blessing,
               bzip2_1_0_5, -- Deprecated as of 3.16
               bzip2_1_0_6,
               copyleft_next_0_3_0,
               copyleft_next_0_3_1,
               curl,
               diffmark,
               dvipdfm,
               eGenix,
               etalab_2_0,
               gSOAP_1_3b,
               gnuplot,
               iMatix,
               libpng_2_0,
               libselinux_1_0,
               libtiff,
               mpich2,
               psfrag,
               psutils,
               xinetd,
               xpp,
               zlib_acknowledgement);

   type String_Access is not null access constant String;
   Img_Ptr : constant array (Id) of String_Access :=
     (
      Id_0BSD => new String'("0BSD"),
      Id_3D_Slicer_1_0 => new String'("3D-Slicer-1.0"),
      AAL => new String'("AAL"),
      AdaCore_doc => new String'("AdaCore-doc"),
      ADSL => new String'("ADSL"),
      AFL_1_1 => new String'("AFL-1.1"),
      AFL_1_2 => new String'("AFL-1.2"),
      AFL_2_0 => new String'("AFL-2.0"),
      AFL_2_1 => new String'("AFL-2.1"),
      AFL_3_0 => new String'("AFL-3.0"),
      AGPL_1_0_only => new String'("AGPL-1.0-only"),
      AGPL_1_0_or_later => new String'("AGPL-1.0-or-later"),
      AGPL_3_0_only => new String'("AGPL-3.0-only"),
      AGPL_3_0_or_later => new String'("AGPL-3.0-or-later"),
      AMD_newlib => new String'("AMD-newlib"),
      AMDPLPA => new String'("AMDPLPA"),
      AML => new String'("AML"),
      AML_glslang => new String'("AML-glslang"),
      AMPAS => new String'("AMPAS"),
      ANTLR_PD => new String'("ANTLR-PD"),
      ANTLR_PD_fallback => new String'("ANTLR-PD-fallback"),
      any_OSI => new String'("any-OSI"),
      APAFML => new String'("APAFML"),
      APL_1_0 => new String'("APL-1.0"),
      APSL_1_0 => new String'("APSL-1.0"),
      APSL_1_1 => new String'("APSL-1.1"),
      APSL_1_2 => new String'("APSL-1.2"),
      APSL_2_0 => new String'("APSL-2.0"),
      App_s2p => new String'("App-s2p"),
      Abstyles => new String'("Abstyles"),
      Adobe_2006 => new String'("Adobe-2006"),
      Adobe_Display_PostScript => new String'("Adobe-Display-PostScript"),
      Adobe_Glyph => new String'("Adobe-Glyph"),
      Adobe_Utopia => new String'("Adobe-Utopia"),
      Afmparse => new String'("Afmparse"),
      Aladdin => new String'("Aladdin"),
      Apache_1_0 => new String'("Apache-1.0"),
      Apache_1_1 => new String'("Apache-1.1"),
      Apache_2_0 => new String'("Apache-2.0"),
      Arphic_1999 => new String'("Arphic-1999"),
      Artistic_1_0 => new String'("Artistic-1.0"),
      Artistic_1_0_Perl => new String'("Artistic-1.0-Perl"),
      Artistic_1_0_cl8 => new String'("Artistic-1.0-cl8"),
      Artistic_2_0 => new String'("Artistic-2.0"),
      ASWF_Digital_Assets_1_0 => new String'("ASWF-Digital-Assets-1.0"),
      ASWF_Digital_Assets_1_1 => new String'("ASWF-Digital-Assets-1.1"),
      Baekmuk => new String'("Baekmuk"),
      bcrypt_Solar_Designer => new String'("bcrypt-Solar-Designer"),
      Bitstream_Charter => new String'("Bitstream-Charter"),
      Bitstream_Vera => new String'("Bitstream-Vera"),
      Boehm_GC => new String'("Boehm-GC"),
      Brian_Gladman_2_Clause => new String'("Brian-Gladman-2-Clause"),
      Brian_Gladman_3_Clause => new String'("Brian-Gladman-3-Clause"),
      BSD_1_Clause => new String'("BSD-1-Clause"),
      BSD_2_Clause => new String'("BSD-2-Clause"),
      BSD_2_Clause_Darwin => new String'("BSD-2-Clause-Darwin"),
      BSD_2_Clause_first_lines => new String'("BSD-2-Clause-first-lines"),
      BSD_2_Clause_Patent => new String'("BSD-2-Clause-Patent"),
      BSD_2_Clause_Views => new String'("BSD-2-Clause-Views"),
      BSD_3_Clause => new String'("BSD-3-Clause"),
      BSD_3_Clause_acpica => new String'("BSD-3-Clause-acpica"),
      BSD_3_Clause_Attribution => new String'("BSD-3-Clause-Attribution"),
      BSD_3_Clause_Clear => new String'("BSD-3-Clause-Clear"),
      BSD_3_Clause_flex => new String'("BSD-3-Clause-flex"),
      BSD_3_Clause_HP => new String'("BSD-3-Clause-HP"),
      BSD_3_Clause_LBNL => new String'("BSD-3-Clause-LBNL"),
      BSD_3_Clause_Modification => new String'("BSD-3-Clause-Modification"),
      BSD_3_Clause_No_Military_License => new String'("BSD-3-Clause-No-Military-License"),
      BSD_3_Clause_No_Nuclear_License => new String'("BSD-3-Clause-No-Nuclear-License"),
      BSD_3_Clause_No_Nuclear_License_2014 => new String'("BSD-3-Clause-No-Nuclear-License-2014"),
      BSD_3_Clause_No_Nuclear_Warranty => new String'("BSD-3-Clause-No-Nuclear-Warranty"),
      BSD_3_Clause_Open_MPI => new String'("BSD-3-Clause-Open-MPI"),
      BSD_3_Clause_Sun => new String'("BSD-3-Clause-Sun"),
      BSD_4_Clause => new String'("BSD-4-Clause"),
      BSD_4_Clause_Shortened => new String'("BSD-4-Clause-Shortened"),
      BSD_4_Clause_UC => new String'("BSD-4-Clause-UC"),
      BSD_4_3RENO => new String'("BSD-4.3RENO"),
      BSD_4_3TAHOE => new String'("BSD-4.3TAHOE"),
      BSD_Advertising_Acknowledgement => new String'("BSD-Advertising-Acknowledgement"),
      BSD_Attribution_HPND_disclaimer => new String'("BSD-Attribution-HPND-disclaimer"),
      BSD_Inferno_Nettverk => new String'("BSD-Inferno-Nettverk"),
      BSD_Protection => new String'("BSD-Protection"),
      BSD_Source_beginning_file => new String'("BSD-Source-beginning-file"),
      BSD_Source_Code => new String'("BSD-Source-Code"),
      BSD_Systemics => new String'("BSD-Systemics"),
      BSD_Systemics_W3Works => new String'("BSD-Systemics-W3Works"),
      BSL_1_0 => new String'("BSL-1.0"),
      Bahyph => new String'("Bahyph"),
      Barr => new String'("Barr"),
      Beerware => new String'("Beerware"),
      BitTorrent_1_0 => new String'("BitTorrent-1.0"),
      BitTorrent_1_1 => new String'("BitTorrent-1.1"),
      BlueOak_1_0_0 => new String'("BlueOak-1.0.0"),
      Borceux => new String'("Borceux"),
      BUSL_1_1 => new String'("BUSL-1.1"),
      C_UDA_1_0 => new String'("C-UDA-1.0"),
      CAL_1_0 => new String'("CAL-1.0"),
      CAL_1_0_Combined_Work_Exception => new String'("CAL-1.0-Combined-Work-Exception"),
      Catharon => new String'("Catharon"),
      CATOSL_1_1 => new String'("CATOSL-1.1"),
      CC_BY_1_0 => new String'("CC-BY-1.0"),
      CC_BY_2_0 => new String'("CC-BY-2.0"),
      CC_BY_2_5 => new String'("CC-BY-2.5"),
      CC_BY_2_5_AU => new String'("CC-BY-2.5-AU"),
      CC_BY_3_0 => new String'("CC-BY-3.0"),
      CC_BY_3_0_AT => new String'("CC-BY-3.0-AT"),
      CC_BY_3_0_AU => new String'("CC-BY-3.0-AU"),
      CC_BY_3_0_DE => new String'("CC-BY-3.0-DE"),
      CC_BY_3_0_IGO => new String'("CC-BY-3.0-IGO"),
      CC_BY_3_0_NL => new String'("CC-BY-3.0-NL"),
      CC_BY_3_0_US => new String'("CC-BY-3.0-US"),
      CC_BY_4_0 => new String'("CC-BY-4.0"),
      CC_BY_NC_1_0 => new String'("CC-BY-NC-1.0"),
      CC_BY_NC_2_0 => new String'("CC-BY-NC-2.0"),
      CC_BY_NC_2_5 => new String'("CC-BY-NC-2.5"),
      CC_BY_NC_3_0 => new String'("CC-BY-NC-3.0"),
      CC_BY_NC_3_0_DE => new String'("CC-BY-NC-3.0-DE"),
      CC_BY_NC_4_0 => new String'("CC-BY-NC-4.0"),
      CC_BY_NC_ND_1_0 => new String'("CC-BY-NC-ND-1.0"),
      CC_BY_NC_ND_2_0 => new String'("CC-BY-NC-ND-2.0"),
      CC_BY_NC_ND_2_5 => new String'("CC-BY-NC-ND-2.5"),
      CC_BY_NC_ND_3_0 => new String'("CC-BY-NC-ND-3.0"),
      CC_BY_NC_ND_3_0_DE => new String'("CC-BY-NC-ND-3.0-DE"),
      CC_BY_NC_ND_3_0_IGO => new String'("CC-BY-NC-ND-3.0-IGO"),
      CC_BY_NC_ND_4_0 => new String'("CC-BY-NC-ND-4.0"),
      CC_BY_NC_SA_1_0 => new String'("CC-BY-NC-SA-1.0"),
      CC_BY_NC_SA_2_0 => new String'("CC-BY-NC-SA-2.0"),
      CC_BY_NC_SA_2_0_DE => new String'("CC-BY-NC-SA-2.0-DE"),
      CC_BY_NC_SA_2_0_FR => new String'("CC-BY-NC-SA-2.0-FR"),
      CC_BY_NC_SA_2_0_UK => new String'("CC-BY-NC-SA-2.0-UK"),
      CC_BY_NC_SA_2_5 => new String'("CC-BY-NC-SA-2.5"),
      CC_BY_NC_SA_3_0 => new String'("CC-BY-NC-SA-3.0"),
      CC_BY_NC_SA_3_0_DE => new String'("CC-BY-NC-SA-3.0-DE"),
      CC_BY_NC_SA_3_0_IGO => new String'("CC-BY-NC-SA-3.0-IGO"),
      CC_BY_NC_SA_4_0 => new String'("CC-BY-NC-SA-4.0"),
      CC_BY_ND_1_0 => new String'("CC-BY-ND-1.0"),
      CC_BY_ND_2_0 => new String'("CC-BY-ND-2.0"),
      CC_BY_ND_2_5 => new String'("CC-BY-ND-2.5"),
      CC_BY_ND_3_0 => new String'("CC-BY-ND-3.0"),
      CC_BY_ND_3_0_DE => new String'("CC-BY-ND-3.0-DE"),
      CC_BY_ND_4_0 => new String'("CC-BY-ND-4.0"),
      CC_BY_SA_1_0 => new String'("CC-BY-SA-1.0"),
      CC_BY_SA_2_0 => new String'("CC-BY-SA-2.0"),
      CC_BY_SA_2_0_UK => new String'("Creative Commons Attribution Share Alike 2.0 England and Wales"),
      CC_BY_SA_2_1_JP => new String'("Creative Commons Attribution Share Alike 2.1 Japan"),
      CC_BY_SA_2_5 => new String'("CC-BY-SA-2.5"),
      CC_BY_SA_3_0 => new String'("CC-BY-SA-3.0"),
      CC_BY_SA_3_0_AT => new String'("CC-BY-SA-3.0-AT"),
      CC_BY_SA_3_0_DE => new String'("CC-BY-SA-3.0-DE"),
      CC_BY_SA_3_0_IGO => new String'("CC-BY-SA-3.0-IGO"),
      CC_BY_SA_4_0 => new String'("CC-BY-SA-4.0"),
      CC_PDDC => new String'("CC-PDDC"),
      CC0_1_0 => new String'("CC0-1.0"),
      CDDL_1_0 => new String'("CDDL-1.0"),
      CDDL_1_1 => new String'("CDDL-1.1"),
      CDL_1_0 => new String'("CDL-1.0"),
      CDLA_Permissive_1_0 => new String'("CDLA-Permissive-1.0"),
      CDLA_Permissive_2_0 => new String'("CDLA-Permissive-2.0"),
      CDLA_Sharing_1_0 => new String'("CDLA-Sharing-1.0"),
      CECILL_1_0 => new String'("CECILL-1.0"),
      CECILL_1_1 => new String'("CECILL-1.1"),
      CECILL_2_0 => new String'("CECILL-2.0"),
      CECILL_2_1 => new String'("CECILL-2.1"),
      CECILL_B => new String'("CECILL-B"),
      CECILL_C => new String'("CECILL-C"),
      CERN_OHL_1_1 => new String'("CERN-OHL-1.1"),
      CERN_OHL_1_2 => new String'("CERN-OHL-1.2"),
      CERN_OHL_P_2_0 => new String'("CERN-OHL-P-2.0"),
      CERN_OHL_S_2_0 => new String'("CERN-OHL-S-2.0"),
      CERN_OHL_W_2_0 => new String'("CERN-OHL-W-2.0"),
      CFITSIO => new String'("CFITSIO"),
      check_cvs => new String'("check-cvs"),
      checkmk => new String'("checkmk"),
      Clips => new String'("Clips"),
      CMU_Mach => new String'("CMU-Mach"),
      CMU_Mach_nodoc => new String'("CMU-Mach-nodoc"),
      CNRI_Jython => new String'("CNRI-Jython"),
      CNRI_Python => new String'("CNRI-Python"),
      CNRI_Python_GPL_Compatible => new String'("CNRI-Python-GPL-Compatible"),
      COIL_1_0 => new String'("COIL-1.0"),
      Community_Spec_1_0 => new String'("Community-Spec-1.0"),
      Cornell_Lossless_JPEG => new String'("Cornell-Lossless-JPEG"),
      CPAL_1_0 => new String'("CPAL-1.0"),
      CPL_1_0 => new String'("CPL-1.0"),
      CPOL_1_02 => new String'("CPOL-1.02"),
      CUA_OPL_1_0 => new String'("CUA-OPL-1.0"),
      Caldera => new String'("Caldera"),
      Caldera_no_preamble => new String'("Caldera-no-preamble"),
      ClArtistic => new String'("ClArtistic"),
      Condor_1_1 => new String'("Condor-1.1"),
      Cronyx => new String'("Cronyx"),
      Crossword => new String'("Crossword"),
      CrystalStacker => new String'("CrystalStacker"),
      Cube => new String'("Cube"),
      cve_tou => new String'("cve-tou"),
      D_FSL_1_0 => new String'("D-FSL-1.0"),
      DEC_3_Clause => new String'("DEC-3-Clause"),
      DL_DE_BY_2_0 => new String'("DL-DE-BY-2.0"),
      DL_DE_ZERO_2_0 => new String'("DL-DE-ZERO-2.0"),
      DOC => new String'("DOC"),
      DSDP => new String'("DSDP"),
      Dotseqn => new String'("Dotseqn"),
      DRL_1_0 => new String'("DRL-1.0"),
      DRL_1_1 => new String'("DRL-1.1"),
      dtoa => new String'("dtoa"),
      ECL_1_0 => new String'("ECL-1.0"),
      ECL_2_0 => new String'("ECL-2.0"),
      EFL_1_0 => new String'("EFL-1.0"),
      EFL_2_0 => new String'("EFL-2.0"),
      Elastic_2_0 => new String'("Elastic-2.0"),
      EPICS => new String'("EPICS"),
      EPL_1_0 => new String'("EPL-1.0"),
      EPL_2_0 => new String'("EPL-2.0"),
      EUDatagrid => new String'("EUDatagrid"),
      EUPL_1_0 => new String'("EUPL-1.0"),
      EUPL_1_1 => new String'("EUPL-1.1"),
      EUPL_1_2 => new String'("EUPL-1.2"),
      Entessa => new String'("Entessa"),
      ErlPL_1_1 => new String'("ErlPL-1.1"),
      Eurosym => new String'("Eurosym"),
      FBM => new String'("FBM"),
      FDK_AAC => new String'("FDK-AAC"),
      Ferguson_Twofish => new String'("Ferguson-Twofish"),
      FreeBSD_DOC => new String'("FreeBSD-DOC"),
      FSFAP => new String'("FSFAP"),
      FSFAP_no_warranty_disclaimer => new String'("FSFAP-no-warranty-disclaimer"),
      FSFUL => new String'("FSFUL"),
      FSFULLR => new String'("FSFULLR"),
      FSFULLRWD => new String'("FSFULLRWD"),
      FTL => new String'("FTL"),
      Fair => new String'("Fair"),
      Frameworx_1_0 => new String'("Frameworx-1.0"),
      FreeImage => new String'("FreeImage"),
      Furuseth => new String'("Furuseth"),
      fwlw => new String'("fwlw"),
      GCR_docs => new String'("GCR-docs"),
      GD => new String'("GD"),
      GFDL_1_1_invariants_only => new String'("GFDL-1.1-invariants-only"),
      GFDL_1_1_invariants_or_later => new String'("GFDL-1.1-invariants-or-later"),
      GFDL_1_1_no_invariants_only => new String'("GFDL-1.1-no-invariants-only"),
      GFDL_1_1_no_invariants_or_later => new String'("GFDL-1.1-no-invariants-or-later"),
      GFDL_1_1_only => new String'("GFDL-1.1-only"),
      GFDL_1_1_or_later => new String'("GFDL-1.1-or-later"),
      GFDL_1_2_invariants_only => new String'("GFDL-1.2-invariants-only"),
      GFDL_1_2_invariants_or_later => new String'("GFDL-1.2-invariants-or-later"),
      GFDL_1_2_no_invariants_only => new String'("GFDL-1.2-no-invariants-only"),
      GFDL_1_2_no_invariants_or_later => new String'("GFDL-1.2-no-invariants-or-later"),
      GFDL_1_2_only => new String'("GFDL-1.2-only"),
      GFDL_1_2_or_later => new String'("GFDL-1.2-or-later"),
      GFDL_1_3_invariants_only => new String'("GFDL-1.3-invariants-only"),
      GFDL_1_3_invariants_or_later => new String'("GFDL-1.3-invariants-or-later"),
      GFDL_1_3_no_invariants_only => new String'("GFDL-1.3-no-invariants-only"),
      GFDL_1_3_no_invariants_or_later => new String'("GFDL-1.3-no-invariants-or-later"),
      GFDL_1_3_only => new String'("GFDL-1.3-only"),
      GFDL_1_3_or_later => new String'("GFDL-1.3-or-later"),
      GL2PS => new String'("GL2PS"),
      GLWTPL => new String'("GLWTPL"),
      GPL_1_0_only => new String'("GPL-1.0-only"),
      GPL_1_0_or_later => new String'("GPL-1.0-or-later"),
      GPL_2_0_only => new String'("GPL-2.0-only"),
      GPL_2_0_or_later => new String'("GPL-2.0-or-later"),
      GPL_3_0_only => new String'("GPL-3.0-only"),
      GPL_3_0_or_later => new String'("GPL-3.0-or-later"),
      Giftware => new String'("Giftware"),
      Glide => new String'("Glide"),
      Glulxe => new String'("Glulxe"),
      HPND => new String'("HPND"),
      HPND_DEC => new String'("HPND-DEC"),
      HPND_doc => new String'("HPND-doc"),
      HPND_doc_sell => new String'("HPND-doc-sell"),
      HPND_export_US => new String'("HPND-export-US"),
      HPND_export_US_acknowledgement => new String'("HPND-export-US-acknowledgement"),
      HPND_export_US_modify => new String'("HPND-export-US-modify"),
      HPND_export2_US => new String'("HPND-export2-US"),
      HPND_Fenneberg_Livingston => new String'("HPND-Fenneberg-Livingston"),
      HPND_INRIA_IMAG => new String'("HPND-INRIA-IMAG"),
      HPND_Intel => new String'("HPND-Intel"),
      HPND_Kevlin_Henney => new String'("HPND-Kevlin-Henney"),
      HPND_Markus_Kuhn => new String'("HPND-Markus-Kuhn"),
      HPND_merchantability_variant => new String'("HPND-merchantability-variant"),
      HPND_MIT_disclaimer => new String'("HPND-MIT-disclaimer"),
      HPND_Pbmplus => new String'("HPND-Pbmplus"),
      HPND_sell_MIT_disclaimer_xserver => new String'("HPND-sell-MIT-disclaimer-xserver"),
      HPND_sell_regexpr => new String'("HPND-sell-regexpr"),
      HPND_sell_variant => new String'("HPND-sell-variant"),
      HPND_sell_variant_MIT_disclaimer => new String'("HPND-sell-variant-MIT-disclaimer"),
      HPND_sell_variant_MIT_disclaimer_rev => new String'("HPND-sell-variant-MIT-disclaimer-rev"),
      Graphics_Gems => new String'("Graphics-Gems"),
      gtkbook => new String'("gtkbook"),
      Gutmann => new String'("Gutmann"),
      HaskellReport => new String'("HaskellReport"),
      hdparm => new String'("hdparm"),
      Hippocratic_2_1 => new String'("Hippocratic-2.1"),
      HP_1986 => new String'("HP-1986"),
      HP_1989 => new String'("HP-1989"),
      HPND_UC => new String'("HPND-UC"),
      HPND_UC_export_US => new String'("HPND-UC-export-US"),
      HTMLTIDY => new String'("HTMLTIDY"),
      IBM_pibs => new String'("IBM-pibs"),
      ICU => new String'("ICU"),
      IEC_Code_Components_EULA => new String'("IEC-Code-Components-EULA"),
      IJG => new String'("IJG"),
      IJG_short => new String'("IJG-short"),
      IPA => new String'("IPA"),
      IPL_1_0 => new String'("IPL-1.0"),
      ISC => new String'("ISC"),
      ImageMagick => new String'("ImageMagick"),
      Imlib2 => new String'("Imlib2"),
      Info_ZIP => new String'("Info-ZIP"),
      Inner_Net_2_0 => new String'("Inner-Net-2.0"),
      Intel => new String'("Intel"),
      Intel_ACPI => new String'("Intel-ACPI"),
      Interbase_1_0 => new String'("Interbase-1.0"),
      ISC_Veillard => new String'("ISC-Veillard"),
      Jam => new String'("Jam"),
      JPL_image => new String'("JPL-image"),
      JPNIC => new String'("JPNIC"),
      JSON => new String'("JSON"),
      JasPer_2_0 => new String'("JasPer-2.0"),
      Kastrup => new String'("Kastrup"),
      Kazlib => new String'("Kazlib"),
      Knuth_CTAN => new String'("Knuth-CTAN"),
      LAL_1_2 => new String'("LAL-1.2"),
      LAL_1_3 => new String'("LAL-1.3"),
      LGPL_2_0_only => new String'("LGPL-2.0-only"),
      LGPL_2_0_or_later => new String'("LGPL-2.0-or-later"),
      LGPL_2_1_only => new String'("LGPL-2.1-only"),
      LGPL_2_1_or_later => new String'("LGPL-2.1-or-later"),
      LGPL_3_0_only => new String'("LGPL-3.0-only"),
      LGPL_3_0_or_later => new String'("LGPL-3.0-or-later"),
      LGPLLR => new String'("LGPLLR"),
      libutil_David_Nugent => new String'("libutil-David-Nugent"),
      Id_LOOP => new String'("LOOP"),
      LPD_document => new String'("LPD-document"),
      LPL_1_0 => new String'("LPL-1.0"),
      LPL_1_02 => new String'("LPL-1.02"),
      LPPL_1_0 => new String'("LPPL-1.0"),
      LPPL_1_1 => new String'("LPPL-1.1"),
      LPPL_1_2 => new String'("LPPL-1.2"),
      LPPL_1_3a => new String'("LPPL-1.3a"),
      LPPL_1_3c => new String'("LPPL-1.3c"),
      Latex2e => new String'("Latex2e"),
      Latex2e_translated_notice => new String'("Latex2e-translated-notice"),
      Leptonica => new String'("Leptonica"),
      LiLiQ_P_1_1 => new String'("LiLiQ-P-1.1"),
      LiLiQ_R_1_1 => new String'("LiLiQ-R-1.1"),
      LiLiQ_Rplus_1_1 => new String'("LiLiQ-Rplus-1.1"),
      Libpng => new String'("Libpng"),
      Linux_man_pages_1_para => new String'("Linux-man-pages-1-para"),
      Linux_man_pages_copyleft => new String'("Linux-man-pages-copyleft"),
      Linux_man_pages_copyleft_2_para => new String'("Linux-man-pages-copyleft-2-para"),
      Linux_man_pages_copyleft_var => new String'("Linux-man-pages-copyleft-var"),
      Linux_OpenIB => new String'("Linux-OpenIB"),
      lsof => new String'("lsof"),
      Lucida_Bitmap_Fonts => new String'("Lucida-Bitmap-Fonts"),
      LZMA_SDK_9_11_to_9_20 => new String'("LZMA-SDK-9.11-to-9.20"),
      LZMA_SDK_9_22 => new String'("LZMA-SDK-9.22"),
      Mackerras_3_Clause => new String'("Mackerras-3-Clause"),
      Mackerras_3_Clause_acknowledgment => new String'("Mackerras-3-Clause-acknowledgment"),
      magaz => new String'("magaz"),
      mailprio => new String'("mailprio"),
      Martin_Birgmeier => new String'("Martin-Birgmeier"),
      McPhee_slideshow => new String'("McPhee-slideshow"),
      metamail => new String'("metamail"),
      Minpack => new String'("Minpack"),
      MIT => new String'("MIT"),
      MIT_0 => new String'("MIT-0"),
      MIT_CMU => new String'("MIT-CMU"),
      MIT_advertising => new String'("MIT-advertising"),
      MIT_enna => new String'("MIT-enna"),
      MIT_feh => new String'("MIT-feh"),
      MIT_Festival => new String'("MIT-Festival"),
      MIT_Khronos_old => new String'("MIT-Khronos-old"),
      MIT_Modern_Variant => new String'("MIT-Modern-Variant"),
      MIT_open_group => new String'("MIT-open-group"),
      MIT_testregex => new String'("MIT-testregex"),
      MIT_Wu => new String'("MIT-Wu"),
      MITNFA => new String'("MITNFA"),
      MMIXware => new String'("MMIXware"),
      MPEG_SSG => new String'("MPEG-SSG"),
      mpi_permissive => new String'("mpi-permissive"),
      MPL_1_0 => new String'("MPL-1.0"),
      MPL_1_1 => new String'("MPL-1.1"),
      MPL_2_0 => new String'("MPL-2.0"),
      MPL_2_0_no_copyleft_exception => new String'("MPL-2.0-no-copyleft-exception"),
      mplus => new String'("mplus"),
      MS_LPL => new String'("MS-LPL"),
      MS_PL => new String'("MS-PL"),
      MS_RL => new String'("MS-RL"),
      MTLL => new String'("MTLL"),
      MakeIndex => new String'("MakeIndex"),
      MirOS => new String'("MirOS"),
      Motosoto => new String'("Motosoto"),
      MulanPSL_1_0 => new String'("MulanPSL-1.0"),
      MulanPSL_2_0 => new String'("MulanPSL-2.0"),
      Multics => new String'("Multics"),
      Mup => new String'("Mup"),
      NAIST_2003 => new String'("NAIST-2003"),
      NASA_1_3 => new String'("NASA-1.3"),
      NBPL_1_0 => new String'("NBPL-1.0"),
      NCBI_PD => new String'("NCBI-PD"),
      NCGL_UK_2_0 => new String'("NCGL-UK-2.0"),
      NCL => new String'("NCL"),
      NCSA => new String'("NCSA"),
      NGPL => new String'("NGPL"),
      NICTA_1_0 => new String'("NICTA-1.0"),
      NIST_PD => new String'("NIST-PD"),
      NIST_PD_fallback => new String'("NIST-PD-fallback"),
      NIST_Software => new String'("NIST-Software"),
      NLOD_1_0 => new String'("NLOD-1.0"),
      NLOD_2_0 => new String'("NLOD-2.0"),
      NLPL => new String'("NLPL"),
      NOSL => new String'("NOSL"),
      NPL_1_0 => new String'("NPL-1.0"),
      NPL_1_1 => new String'("NPL-1.1"),
      NPOSL_3_0 => new String'("NPOSL-3.0"),
      NRL => new String'("NRL"),
      NTP => new String'("NTP"),
      NTP_0 => new String'("NTP-0"),
      Naumen => new String'("Naumen"),
      Net_SNMP => new String'("Net-SNMP"),
      NetCDF => new String'("NetCDF"),
      Newsletr => new String'("Newsletr"),
      Nokia => new String'("Nokia"),
      Noweb => new String'("Noweb"),
      O_UDA_1_0 => new String'("O-UDA-1.0"),
      OAR => new String'("OAR"),
      OCCT_PL => new String'("OCCT-PL"),
      OCLC_2_0 => new String'("OCLC-2.0"),
      ODC_By_1_0 => new String'("ODC-By-1.0"),
      ODbL_1_0 => new String'("ODbL-1.0"),
      OFFIS => new String'("OFFIS"),
      OFL_1_0 => new String'("OFL-1.0"),
      OFL_1_0_RFN => new String'("OFL-1.0-RFN"),
      OFL_1_0_no_RFN => new String'("OFL-1.0-no-RFN"),
      OFL_1_1 => new String'("OFL-1.1"),
      OFL_1_1_RFN => new String'("OFL-1.1-RFN"),
      OFL_1_1_no_RFN => new String'("OFL-1.1-no-RFN"),
      OGC_1_0 => new String'("OGC-1.0"),
      OGDL_Taiwan_1_0 => new String'("OGDL-Taiwan-1.0"),
      OGL_Canada_2_0 => new String'("OGL-Canada-2.0"),
      OGL_UK_1_0 => new String'("OGL-UK-1.0"),
      OGL_UK_2_0 => new String'("OGL-UK-2.0"),
      OGL_UK_3_0 => new String'("OGL-UK-3.0"),
      OGTSL => new String'("OGTSL"),
      OLDAP_1_1 => new String'("OLDAP-1.1"),
      OLDAP_1_2 => new String'("OLDAP-1.2"),
      OLDAP_1_3 => new String'("OLDAP-1.3"),
      OLDAP_1_4 => new String'("OLDAP-1.4"),
      OLDAP_2_0 => new String'("OLDAP-2.0"),
      OLDAP_2_0_1 => new String'("OLDAP-2.0.1"),
      OLDAP_2_1 => new String'("OLDAP-2.1"),
      OLDAP_2_2 => new String'("OLDAP-2.2"),
      OLDAP_2_2_1 => new String'("OLDAP-2.2.1"),
      OLDAP_2_2_2 => new String'("OLDAP-2.2.2"),
      OLDAP_2_3 => new String'("OLDAP-2.3"),
      OLDAP_2_4 => new String'("OLDAP-2.4"),
      OLDAP_2_5 => new String'("OLDAP-2.5"),
      OLDAP_2_6 => new String'("OLDAP-2.6"),
      OLDAP_2_7 => new String'("OLDAP-2.7"),
      OLDAP_2_8 => new String'("OLDAP-2.8"),
      OLFL_1_3 => new String'("OLFL-1.3"),
      OML => new String'("OML"),
      OpenPBS_2_3 => new String'("OpenPBS-2.3"),
      OpenVision => new String'("OpenVision"),
      OPL_1_0 => new String'("OPL-1.0"),
      OPL_UK_3_0 => new String'("OPL-UK-3.0"),
      OPUBL_1_0 => new String'("OPUBL-1.0"),
      OSET_PL_2_1 => new String'("OSET-PL-2.1"),
      OSL_1_0 => new String'("OSL-1.0"),
      OSL_1_1 => new String'("OSL-1.1"),
      OSL_2_0 => new String'("OSL-2.0"),
      OSL_2_1 => new String'("OSL-2.1"),
      OSL_3_0 => new String'("OSL-3.0"),
      OpenSSL => new String'("OpenSSL"),
      OpenSSL_standalone => new String'("OpenSSL-standalone"),
      PADL => new String'("PADL"),
      PDDL_1_0 => new String'("PDDL-1.0"),
      PHP_3_0 => new String'("PHP-3.0"),
      PHP_3_01 => new String'("PHP-3.01"),
      PSF_2_0 => new String'("PSF-2.0"),
      Parity_6_0_0 => new String'("Parity-6.0.0"),
      Parity_7_0_0 => new String'("Parity-7.0.0"),
      Pixar => new String'("Pixar"),
      pkgconf => new String'("pkgconf"),
      Plexus => new String'("Plexus"),
      pnmstitch => new String'("pnmstitch"),
      PolyForm_Noncommercial_1_0_0 => new String'("PolyForm-Noncommercial-1.0.0"),
      PolyForm_Small_Business_1_0_0 => new String'("PolyForm-Small-Business-1.0.0"),
      PostgreSQL => new String'("PostgreSQL"),
      PPL => new String'("PPL"),
      Python_2_0 => new String'("Python-2.0"),
      Python_2_0_1 => new String'("Python-2.0.1"),
      QPL_1_0 => new String'("QPL-1.0"),
      QPL_1_0_INRIA_2004 => new String'("QPL-1.0-INRIA-2004"),
      python_ldap => new String'("python-ldap"),
      Qhull => new String'("Qhull"),
      radvd => new String'("radvd"),
      RHeCos_1_1 => new String'("RHeCos-1.1"),
      RPL_1_1 => new String'("RPL-1.1"),
      RPL_1_5 => new String'("RPL-1.5"),
      RPSL_1_0 => new String'("RPSL-1.0"),
      RSA_MD => new String'("RSA-MD"),
      RSCPL => new String'("RSCPL"),
      Rdisc => new String'("Rdisc"),
      Ruby => new String'("Ruby"),
      SAX_PD => new String'("SAX-PD"),
      SAX_PD_2_0 => new String'("SAX-PD-2.0"),
      SCEA => new String'("SCEA"),
      SchemeReport => new String'("SchemeReport"),
      SGI_B_1_0 => new String'("SGI-B-1.0"),
      SGI_B_1_1 => new String'("SGI-B-1.1"),
      SGI_B_2_0 => new String'("SGI-B-2.0"),
      SGI_OpenGL => new String'("SGI-OpenGL"),
      SGP4 => new String'("SGP4"),
      SHL_0_5 => new String'("SHL-0.5"),
      SHL_0_51 => new String'("SHL-0.51"),
      SISSL => new String'("SISSL"),
      SISSL_1_2 => new String'("SISSL-1.2"),
      SL => new String'("SL"),
      SMLNJ => new String'("SMLNJ"),
      SMPPL => new String'("SMPPL"),
      SNIA => new String'("SNIA"),
      snprintf => new String'("snprintf"),
      softSurfer => new String'("softSurfer"),
      Soundex => new String'("Soundex"),
      SPL_1_0 => new String'("SPL-1.0"),
      ssh_keyscan => new String'("ssh-keyscan"),
      SSH_OpenSSH => new String'("SSH-OpenSSH"),
      SSH_short => new String'("SSH-short"),
      SSLeay_standalone => new String'("SSLeay-standalone"),
      SSPL_1_0 => new String'("SSPL-1.0"),
      SWL => new String'("SWL"),
      Saxpath => new String'("Saxpath"),
      Sendmail => new String'("Sendmail"),
      Sendmail_8_23 => new String'("Sendmail-8.23"),
      SimPL_2_0 => new String'("SimPL-2.0"),
      Sleepycat => new String'("Sleepycat"),
      Spencer_86 => new String'("Spencer-86"),
      Spencer_94 => new String'("Spencer-94"),
      Spencer_99 => new String'("Spencer-99"),
      SugarCRM_1_1_3 => new String'("SugarCRM-1.1.3"),
      Sun_PPP => new String'("Sun-PPP"),
      Sun_PPP_2000 => new String'("Sun-PPP-2000"),
      SunPro => new String'("SunPro"),
      swrule => new String'("swrule"),
      Symlinks => new String'("Symlinks"),
      TAPR_OHL_1_0 => new String'("TAPR-OHL-1.0"),
      TCL => new String'("TCL"),
      TCP_wrappers => new String'("TCP-wrappers"),
      TermReadKey => new String'("TermReadKey"),
      TGPPL_1_0 => new String'("TGPPL-1.0"),
      threeparttable => new String'("threeparttable"),
      TMate => new String'("TMate"),
      TORQUE_1_1 => new String'("TORQUE-1.1"),
      TOSL => new String'("TOSL"),
      TPDL => new String'("TPDL"),
      TPL_1_0 => new String'("TPL-1.0"),
      TTWL => new String'("TTWL"),
      TTYP0 => new String'("TTYP0"),
      TU_Berlin_1_0 => new String'("TU-Berlin-1.0"),
      TU_Berlin_2_0 => new String'("TU-Berlin-2.0"),
      UCAR => new String'("UCAR"),
      UCL_1_0 => new String'("UCL-1.0"),
      UPL_1_0 => new String'("UPL-1.0"),
      ulem => new String'("ulem"),
      UMich_Merit => new String'("UMich-Merit"),
      Unicode_3_0 => new String'("Unicode-3.0"),
      Unicode_DFS_2015 => new String'("Unicode-DFS-2015"),
      Unicode_DFS_2016 => new String'("Unicode-DFS-2016"),
      Unicode_TOU => new String'("Unicode-TOU"),
      UnixCrypt => new String'("UnixCrypt"),
      Unlicense => new String'("Unlicense"),
      URT_RLE => new String'("URT-RLE"),
      VOSTROM => new String'("VOSTROM"),
      VSL_1_0 => new String'("VSL-1.0"),
      Vim => new String'("Vim"),
      W3C => new String'("W3C"),
      W3C_19980720 => new String'("W3C-19980720"),
      W3C_20150513 => new String'("W3C-20150513"),
      WTFPL => new String'("WTFPL"),
      w3m => new String'("w3m"),
      Watcom_1_0 => new String'("Watcom-1.0"),
      Widget_Workshop => new String'("Widget-Workshop"),
      Wsuipa => new String'("Wsuipa"),
      X11 => new String'("X11"),
      X11_distribute_modifications_variant => new String'("X11-distribute-modifications-variant"),
      XFree86_1_1 => new String'("XFree86-1.1"),
      XSkat => new String'("XSkat"),
      Xdebug_1_03 => new String'("Xdebug-1.03"),
      Xerox => new String'("Xerox"),
      Xfig => new String'("Xfig"),
      xkeyboard_config_Zinoviev => new String'("xkeyboard-config-Zinoviev"),
      xlock => new String'("xlock"),
      Xnet => new String'("Xnet"),
      xzoom => new String'("xzoom"),
      YPL_1_0 => new String'("YPL-1.0"),
      YPL_1_1 => new String'("YPL-1.1"),
      ZPL_1_1 => new String'("ZPL-1.1"),
      ZPL_2_0 => new String'("ZPL-2.0"),
      ZPL_2_1 => new String'("ZPL-2.1"),
      Zed => new String'("Zed"),
      Zeeff => new String'("Zeeff"),
      Zend_2_0 => new String'("Zend-2.0"),
      Zimbra_1_3 => new String'("Zimbra-1.3"),
      Zimbra_1_4 => new String'("Zimbra-1.4"),
      Zlib => new String'("Zlib"),
      blessing => new String'("blessing"),
      bzip2_1_0_5 => new String'("bzip2-1.0.5"),
      bzip2_1_0_6 => new String'("bzip2-1.0.6"),
      copyleft_next_0_3_0 => new String'("copyleft-next-0.3.0"),
      copyleft_next_0_3_1 => new String'("copyleft-next-0.3.1"),
      curl => new String'("curl"),
      diffmark => new String'("diffmark"),
      dvipdfm => new String'("dvipdfm"),
      eGenix => new String'("eGenix"),
      etalab_2_0 => new String'("etalab-2.0"),
      gSOAP_1_3b => new String'("gSOAP-1.3b"),
      gnuplot => new String'("gnuplot"),
      iMatix => new String'("iMatix"),
      libpng_2_0 => new String'("libpng-2.0"),
      libselinux_1_0 => new String'("libselinux-1.0"),
      libtiff => new String'("libtiff"),
      mpich2 => new String'("mpich2"),
      psfrag => new String'("psfrag"),
      psutils => new String'("psutils"),
      xinetd => new String'("xinetd"),
      xpp => new String'("xpp"),
      zlib_acknowledgement => new String'("zlib-acknowledgement"));

   function Img (I : Id) return String
   is (Img_Ptr (I).all);

   Name_Ptr : constant array (Id) of String_Access :=
     (
      Id_0BSD => new String'("BSD Zero Clause License"),
      Id_3D_Slicer_1_0 => new String'("3D Slicer License v1.0"),
      AAL => new String'("Attribution Assurance License"),
      AdaCore_doc => new String'("AdaCore Doc License"),
      ADSL => new String'("Amazon Digital Services License"),
      AFL_1_1 => new String'("Academic Free License v1.1"),
      AFL_1_2 => new String'("Academic Free License v1.2"),
      AFL_2_0 => new String'("Academic Free License v2.0"),
      AFL_2_1 => new String'("Academic Free License v2.1"),
      AFL_3_0 => new String'("Academic Free License v3.0"),
      AGPL_1_0_only => new String'("Affero General Public License v1.0 only"),
      AGPL_1_0_or_later => new String'("Affero General Public License v1.0 or later"),
      AGPL_3_0_only => new String'("GNU Affero General Public License v3.0 only"),
      AGPL_3_0_or_later => new String'("GNU Affero General Public License v3.0 or later"),
      AMD_newlib => new String'("AMD newlib License"),
      AMDPLPA => new String'("AMD's plpa_map.c License"),
      AML => new String'("Apple MIT License"),
      AML_glslang => new String'("AML glslang variant License"),
      AMPAS => new String'("Academy of Motion Picture Arts and Sciences BSD"),
      ANTLR_PD => new String'("ANTLR Software Rights Notice"),
      ANTLR_PD_fallback => new String'("ANTLR Software Rights Notice with license fallback"),
      any_OSI => new String'("Any OSI License"),
      APAFML => new String'("Adobe Postscript AFM License"),
      APL_1_0 => new String'("Adaptive Public License 1.0"),
      APSL_1_0 => new String'("Apple Public Source License 1.0"),
      APSL_1_1 => new String'("Apple Public Source License 1.1"),
      APSL_1_2 => new String'("Apple Public Source License 1.2"),
      APSL_2_0 => new String'("Apple Public Source License 2.0"),
      App_s2p => new String'("App::s2p License"),
      Abstyles => new String'("Abstyles License"),
      Adobe_2006 => new String'("Adobe Systems Incorporated Source Code License Agreement"),
      Adobe_Display_PostScript => new String'("Adobe Display PostScript License"),
      Adobe_Glyph => new String'("Adobe Glyph List License"),
      Adobe_Utopia => new String'("Adobe Utopia Font License"),
      Afmparse => new String'("Afmparse License"),
      Aladdin => new String'("Aladdin Free Public License"),
      Apache_1_0 => new String'("Apache License 1.0"),
      Apache_1_1 => new String'("Apache License 1.1"),
      Apache_2_0 => new String'("Apache License 2.0"),
      Arphic_1999 => new String'("Arphic Public License"),
      Artistic_1_0 => new String'("Artistic License 1.0"),
      Artistic_1_0_Perl => new String'("Artistic License 1.0 (Perl)"),
      Artistic_1_0_cl8 => new String'("Artistic License 1.0 w/clause 8"),
      Artistic_2_0 => new String'("Artistic License 2.0"),
      ASWF_Digital_Assets_1_0 => new String'("ASWF Digital Assets License version 1.0"),
      ASWF_Digital_Assets_1_1 => new String'("ASWF Digital Assets License 1.1"),
      Baekmuk => new String'("Baekmuk License"),
      bcrypt_Solar_Designer => new String'("bcrypt Solar Designer License"),
      Bitstream_Charter => new String'("Bitstream Charter Font License"),
      Bitstream_Vera => new String'("Bitstream Vera Font License"),
      Boehm_GC => new String'("Boehm-Demers-Weiser GC License"),
      Brian_Gladman_2_Clause => new String'("Brian Gladman 2-Clause License"),
      Brian_Gladman_3_Clause => new String'("Brian Gladman 3-Clause License"),
      BSD_1_Clause => new String'("BSD 1-Clause License"),
      BSD_2_Clause => new String'("BSD 2-Clause ""Simplified"" License"),
      BSD_2_Clause_Darwin => new String'("BSD 2-Clause - Ian Darwin variant"),
      BSD_2_Clause_first_lines => new String'("BSD 2-Clause - first lines requirement"),
      BSD_2_Clause_Patent => new String'("BSD-2-Clause Plus Patent License"),
      BSD_2_Clause_Views => new String'("BSD 2-Clause with views sentence"),
      BSD_3_Clause => new String'("BSD 3-Clause ""New"" or ""Revised"" License"),
      BSD_3_Clause_acpica => new String'("BSD 3-Clause acpica variant"),
      BSD_3_Clause_Attribution => new String'("BSD with attribution"),
      BSD_3_Clause_Clear => new String'("BSD 3-Clause Clear License"),
      BSD_3_Clause_flex => new String'("BSD 3-Clause Flex variant"),
      BSD_3_Clause_HP => new String'("Hewlett-Packard BSD variant license"),
      BSD_3_Clause_LBNL => new String'("Lawrence Berkeley National Labs BSD variant license"),
      BSD_3_Clause_Modification => new String'("BSD 3-Clause Modification"),
      BSD_3_Clause_No_Military_License => new String'("BSD 3-Clause No Military License"),
      BSD_3_Clause_No_Nuclear_License => new String'("BSD 3-Clause No Nuclear License"),
      BSD_3_Clause_No_Nuclear_License_2014 => new String'("BSD 3-Clause No Nuclear License 2014"),
      BSD_3_Clause_No_Nuclear_Warranty => new String'("BSD 3-Clause No Nuclear Warranty"),
      BSD_3_Clause_Open_MPI => new String'("BSD 3-Clause Open MPI variant"),
      BSD_3_Clause_Sun => new String'("BSD 3-Clause Sun Microsystems"),
      BSD_4_Clause => new String'("BSD 4-Clause ""Original"" or ""Old"" License"),
      BSD_4_Clause_Shortened => new String'("BSD 4 Clause Shortened"),
      BSD_4_Clause_UC => new String'("BSD-4-Clause (University of California-Specific)"),
      BSD_4_3RENO => new String'("BSD 4.3 RENO License"),
      BSD_4_3TAHOE => new String'("BSD 4.3 TAHOE License"),
      BSD_Advertising_Acknowledgement => new String'("BSD Advertising Acknowledgement License"),
      BSD_Attribution_HPND_disclaimer => new String'("BSD with Attribution and HPND disclaimer"),
      BSD_Inferno_Nettverk => new String'("BSD-Inferno-Nettverk"),
      BSD_Protection => new String'("BSD Protection License"),
      BSD_Source_beginning_file => new String'("BSD Source Code Attribution - beginning of file variant"),
      BSD_Source_Code => new String'("BSD Source Code Attribution"),
      BSD_Systemics => new String'("Systemics BSD variant license"),
      BSD_Systemics_W3Works => new String'("Systemics W3Works BSD variant license"),
      BSL_1_0 => new String'("Boost Software License 1.0"),
      Bahyph => new String'("Bahyph License"),
      Barr => new String'("Barr License"),
      Beerware => new String'("Beerware License"),
      BitTorrent_1_0 => new String'("BitTorrent Open Source License v1.0"),
      BitTorrent_1_1 => new String'("BitTorrent Open Source License v1.1"),
      BlueOak_1_0_0 => new String'("Blue Oak Model License 1.0.0"),
      Borceux => new String'("Borceux license"),
      BUSL_1_1 => new String'("Business Source License 1.1"),
      C_UDA_1_0 => new String'("Computational Use of Data Agreement v1.0"),
      CAL_1_0 => new String'("Cryptographic Autonomy License 1.0"),
      CAL_1_0_Combined_Work_Exception => new String'("Cryptographic Autonomy License 1.0 (Combined Work Exception)"),
      Catharon => new String'("Catharon License"),
      CATOSL_1_1 => new String'("Computer Associates Trusted Open Source License 1.1"),
      CC_BY_1_0 => new String'("Creative Commons Attribution 1.0 Generic"),
      CC_BY_2_0 => new String'("Creative Commons Attribution 2.0 Generic"),
      CC_BY_2_5 => new String'("Creative Commons Attribution 2.5 Generic"),
      CC_BY_2_5_AU => new String'("Creative Commons Attribution 2.5 Australia"),
      CC_BY_3_0 => new String'("Creative Commons Attribution 3.0 Unported"),
      CC_BY_3_0_AT => new String'("Creative Commons Attribution 3.0 Austria"),
      CC_BY_3_0_AU => new String'("Creative Commons Attribution 3.0 Australia"),
      CC_BY_3_0_DE => new String'("Creative Commons Attribution 3.0 Germany"),
      CC_BY_3_0_IGO => new String'("Creative Commons Attribution 3.0 IGO"),
      CC_BY_3_0_NL => new String'("Creative Commons Attribution 3.0 Netherlands"),
      CC_BY_3_0_US => new String'("Creative Commons Attribution 3.0 United States"),
      CC_BY_4_0 => new String'("Creative Commons Attribution 4.0 International"),
      CC_BY_NC_1_0 => new String'("Creative Commons Attribution Non Commercial 1.0 Generic"),
      CC_BY_NC_2_0 => new String'("Creative Commons Attribution Non Commercial 2.0 Generic"),
      CC_BY_NC_2_5 => new String'("Creative Commons Attribution Non Commercial 2.5 Generic"),
      CC_BY_NC_3_0 => new String'("Creative Commons Attribution Non Commercial 3.0 Unported"),
      CC_BY_NC_3_0_DE => new String'("Creative Commons Attribution Non Commercial 3.0 Germany"),
      CC_BY_NC_4_0 => new String'("Creative Commons Attribution Non Commercial 4.0 International"),
      CC_BY_NC_ND_1_0 => new String'("Creative Commons Attribution Non Commercial No Derivatives 1.0 Generic"),
      CC_BY_NC_ND_2_0 => new String'("Creative Commons Attribution Non Commercial No Derivatives 2.0 Generic"),
      CC_BY_NC_ND_2_5 => new String'("Creative Commons Attribution Non Commercial No Derivatives 2.5 Generic"),
      CC_BY_NC_ND_3_0 => new String'("Creative Commons Attribution Non Commercial No Derivatives 3.0 Unported"),
      CC_BY_NC_ND_3_0_DE => new String'("Creative Commons Attribution Non Commercial No Derivatives 3.0 Germany"),
      CC_BY_NC_ND_3_0_IGO => new String'("Creative Commons Attribution Non Commercial No Derivatives 3.0 IGO"),
      CC_BY_NC_ND_4_0 => new String'("Creative Commons Attribution Non Commercial No Derivatives 4.0 International"),
      CC_BY_NC_SA_1_0 => new String'("Creative Commons Attribution Non Commercial Share Alike 1.0 Generic"),
      CC_BY_NC_SA_2_0 => new String'("Creative Commons Attribution Non Commercial Share Alike 2.0 Generic"),
      CC_BY_NC_SA_2_0_DE => new String'("Creative Commons Attribution Non Commercial Share Alike 2.0 Germany"),
      CC_BY_NC_SA_2_0_FR => new String'("Creative Commons Attribution-NonCommercial-ShareAlike 2.0 France"),
      CC_BY_NC_SA_2_0_UK => new String'("Creative Commons Attribution Non Commercial Share Alike 2.0 England and Wales"),
      CC_BY_NC_SA_2_5 => new String'("Creative Commons Attribution Non Commercial Share Alike 2.5 Generic"),
      CC_BY_NC_SA_3_0 => new String'("Creative Commons Attribution Non Commercial Share Alike 3.0 Unported"),
      CC_BY_NC_SA_3_0_DE => new String'("Creative Commons Attribution Non Commercial Share Alike 3.0 Germany"),
      CC_BY_NC_SA_3_0_IGO => new String'("Creative Commons Attribution Non Commercial Share Alike 3.0 IGO"),
      CC_BY_NC_SA_4_0 => new String'("Creative Commons Attribution Non Commercial Share Alike 4.0 International"),
      CC_BY_ND_1_0 => new String'("Creative Commons Attribution No Derivatives 1.0 Generic"),
      CC_BY_ND_2_0 => new String'("Creative Commons Attribution No Derivatives 2.0 Generic"),
      CC_BY_ND_2_5 => new String'("Creative Commons Attribution No Derivatives 2.5 Generic"),
      CC_BY_ND_3_0 => new String'("Creative Commons Attribution No Derivatives 3.0 Unported"),
      CC_BY_ND_3_0_DE => new String'("Creative Commons Attribution No Derivatives 3.0 Germany"),
      CC_BY_ND_4_0 => new String'("Creative Commons Attribution No Derivatives 4.0 International"),
      CC_BY_SA_1_0 => new String'("Creative Commons Attribution Share Alike 1.0 Generic"),
      CC_BY_SA_2_0 => new String'("Creative Commons Attribution Share Alike 2.0 Generic"),
      CC_BY_SA_2_0_UK => new String'("Creative Commons Attribution Share Alike 2.0 England and Wales"),
      CC_BY_SA_2_1_JP => new String'("Creative Commons Attribution Share Alike 2.1 Japan"),
      CC_BY_SA_2_5 => new String'("Creative Commons Attribution Share Alike 2.5 Generic"),
      CC_BY_SA_3_0 => new String'("Creative Commons Attribution Share Alike 3.0 Unported"),
      CC_BY_SA_3_0_AT => new String'("Creative Commons Attribution Share Alike 3.0 Austria"),
      CC_BY_SA_3_0_DE => new String'("Creative Commons Attribution Share Alike 3.0 Germany"),
      CC_BY_SA_3_0_IGO => new String'("Creative Commons Attribution-ShareAlike 3.0 IGO"),
      CC_BY_SA_4_0 => new String'("Creative Commons Attribution Share Alike 4.0 International"),
      CC_PDDC => new String'("Creative Commons Public Domain Dedication and Certification"),
      CC0_1_0 => new String'("Creative Commons Zero v1.0 Universal"),
      CDDL_1_0 => new String'("Common Development and Distribution License 1.0"),
      CDDL_1_1 => new String'("Common Development and Distribution License 1.1"),
      CDL_1_0 => new String'("Common Documentation License 1.0"),
      CDLA_Permissive_1_0 => new String'("Community Data License Agreement Permissive 1.0"),
      CDLA_Permissive_2_0 => new String'("Community Data License Agreement Permissive 2.0"),
      CDLA_Sharing_1_0 => new String'("Community Data License Agreement Sharing 1.0"),
      CECILL_1_0 => new String'("CeCILL Free Software License Agreement v1.0"),
      CECILL_1_1 => new String'("CeCILL Free Software License Agreement v1.1"),
      CECILL_2_0 => new String'("CeCILL Free Software License Agreement v2.0"),
      CECILL_2_1 => new String'("CeCILL Free Software License Agreement v2.1"),
      CECILL_B => new String'("CeCILL-B Free Software License Agreement"),
      CECILL_C => new String'("CeCILL-C Free Software License Agreement"),
      CERN_OHL_1_1 => new String'("CERN Open Hardware Licence v1.1"),
      CERN_OHL_1_2 => new String'("CERN Open Hardware Licence v1.2"),
      CERN_OHL_P_2_0 => new String'("CERN Open Hardware Licence Version 2 - Permissive"),
      CERN_OHL_S_2_0 => new String'("CERN Open Hardware Licence Version 2 - Strongly Reciprocal"),
      CERN_OHL_W_2_0 => new String'("CERN Open Hardware Licence Version 2 - Weakly Reciprocal"),
      CFITSIO => new String'("CFITSIO License"),
      check_cvs => new String'("check-cvs License"),
      checkmk => new String'("Checkmk License"),
      Clips => new String'("Clips License"),
      CMU_Mach => new String'("CMU Mach License"),
      CMU_Mach_nodoc => new String'("CMU Mach - no notices-in-documentation variant"),
      CNRI_Jython => new String'("CNRI Jython License"),
      CNRI_Python => new String'("CNRI Python License"),
      CNRI_Python_GPL_Compatible => new String'("CNRI Python Open Source GPL Compatible License Agreement"),
      COIL_1_0 => new String'("Copyfree Open Innovation License"),
      Community_Spec_1_0 => new String'("Community Specification License 1.0"),
      Cornell_Lossless_JPEG => new String'("Cornell Lossless JPEG License"),
      CPAL_1_0 => new String'("Common Public Attribution License 1.0"),
      CPL_1_0 => new String'("Common Public License 1.0"),
      CPOL_1_02 => new String'("Code Project Open License 1.02"),
      CUA_OPL_1_0 => new String'("CUA Office Public License v1.0"),
      Caldera => new String'("Caldera License"),
      Caldera_no_preamble => new String'("Caldera License (without preamble)"),
      ClArtistic => new String'("Clarified Artistic License"),
      Condor_1_1 => new String'("Condor Public License v1.1"),
      Cronyx => new String'("Cronyx License"),
      Crossword => new String'("Crossword License"),
      CrystalStacker => new String'("CrystalStacker License"),
      Cube => new String'("Cube License"),
      cve_tou => new String'("Common Vulnerability Enumeration ToU License"),
      D_FSL_1_0 => new String'("Deutsche Freie Software Lizenz"),
      DEC_3_Clause => new String'("DEC 3-Clause License"),
      DL_DE_BY_2_0 => new String'("Data licence Germany â€“ attribution â€“ version 2.0"),
      DL_DE_ZERO_2_0 => new String'("Data licence Germany â€“ zero â€“ version 2.0"),
      DOC => new String'("DOC License"),
      DSDP => new String'("DSDP License"),
      Dotseqn => new String'("Dotseqn License"),
      DRL_1_0 => new String'("Detection Rule License 1.0"),
      DRL_1_1 => new String'("Detection Rule License 1.1"),
      dtoa => new String'("David M. Gay dtoa License"),
      ECL_1_0 => new String'("Educational Community License v1.0"),
      ECL_2_0 => new String'("Educational Community License v2.0"),
      EFL_1_0 => new String'("Eiffel Forum License v1.0"),
      EFL_2_0 => new String'("Eiffel Forum License v2.0"),
      Elastic_2_0 => new String'("Elastic License 2.0"),
      EPICS => new String'("EPICS Open License"),
      EPL_1_0 => new String'("Eclipse Public License 1.0"),
      EPL_2_0 => new String'("Eclipse Public License 2.0"),
      EUDatagrid => new String'("EU DataGrid Software License"),
      EUPL_1_0 => new String'("European Union Public License 1.0"),
      EUPL_1_1 => new String'("European Union Public License 1.1"),
      EUPL_1_2 => new String'("European Union Public License 1.2"),
      Entessa => new String'("Entessa Public License v1.0"),
      ErlPL_1_1 => new String'("Erlang Public License v1.1"),
      Eurosym => new String'("Eurosym License"),
      FBM => new String'("Fuzzy Bitmap License"),
      FDK_AAC => new String'("Fraunhofer FDK AAC Codec Library"),
      Ferguson_Twofish => new String'("Ferguson Twofish License"),
      FreeBSD_DOC => new String'("FreeBSD Documentation License"),
      FSFAP => new String'("FSF All Permissive License"),
      FSFAP_no_warranty_disclaimer => new String'("FSF All Permissive License (without Warranty)"),
      FSFUL => new String'("FSF Unlimited License"),
      FSFULLR => new String'("FSF Unlimited License (with License Retention)"),
      FSFULLRWD => new String'("FSF Unlimited License (With License Retention and Warranty Disclaimer)"),
      FTL => new String'("Freetype Project License"),
      Fair => new String'("Fair License"),
      Frameworx_1_0 => new String'("Frameworx Open License 1.0"),
      FreeImage => new String'("FreeImage Public License v1.0"),
      Furuseth => new String'("Furuseth License"),
      fwlw => new String'("fwlw License"),
      GCR_docs => new String'("Gnome GCR Documentation License"),
      GD => new String'("GD License"),
      GFDL_1_1_invariants_only => new String'("GNU Free Documentation License v1.1 only - invariants"),
      GFDL_1_1_invariants_or_later => new String'("GNU Free Documentation License v1.1 or later - invariants"),
      GFDL_1_1_no_invariants_only => new String'("GNU Free Documentation License v1.1 only - no invariants"),
      GFDL_1_1_no_invariants_or_later => new String'("GNU Free Documentation License v1.1 or later - no invariants"),
      GFDL_1_1_only => new String'("GNU Free Documentation License v1.1 only"),
      GFDL_1_1_or_later => new String'("GNU Free Documentation License v1.1 or later"),
      GFDL_1_2_invariants_only => new String'("GNU Free Documentation License v1.2 only - invariants"),
      GFDL_1_2_invariants_or_later => new String'("GNU Free Documentation License v1.2 or later - invariants"),
      GFDL_1_2_no_invariants_only => new String'("GNU Free Documentation License v1.2 only - no invariants"),
      GFDL_1_2_no_invariants_or_later => new String'("GNU Free Documentation License v1.2 or later - no invariants"),
      GFDL_1_2_only => new String'("GNU Free Documentation License v1.2 only"),
      GFDL_1_2_or_later => new String'("GNU Free Documentation License v1.2 or later"),
      GFDL_1_3_invariants_only => new String'("GNU Free Documentation License v1.3 only - invariants"),
      GFDL_1_3_invariants_or_later => new String'("GNU Free Documentation License v1.3 or later - invariants"),
      GFDL_1_3_no_invariants_only => new String'("GNU Free Documentation License v1.3 only - no invariants"),
      GFDL_1_3_no_invariants_or_later => new String'("GNU Free Documentation License v1.3 or later - no invariants"),
      GFDL_1_3_only => new String'("GNU Free Documentation License v1.3 only"),
      GFDL_1_3_or_later => new String'("GNU Free Documentation License v1.3 or later"),
      GL2PS => new String'("GL2PS License"),
      GLWTPL => new String'("Good Luck With That Public License"),
      GPL_1_0_only => new String'("GNU General Public License v1.0 only"),
      GPL_1_0_or_later => new String'("GNU General Public License v1.0 or later"),
      GPL_2_0_only => new String'("GNU General Public License v2.0 only"),
      GPL_2_0_or_later => new String'("GNU General Public License v2.0 or later"),
      GPL_3_0_only => new String'("GNU General Public License v3.0 only"),
      GPL_3_0_or_later => new String'("GNU General Public License v3.0 or later"),
      Giftware => new String'("Giftware License"),
      Glide => new String'("3dfx Glide License"),
      Glulxe => new String'("Glulxe License"),
      HPND => new String'("Historical Permission Notice and Disclaimer"),
      HPND_DEC => new String'("Historical Permission Notice and Disclaimer - DEC variant"),
      HPND_doc => new String'("Historical Permission Notice and Disclaimer - documentation variant"),
      HPND_doc_sell => new String'("Historical Permission Notice and Disclaimer - documentation sell variant"),
      HPND_export_US => new String'("HPND with US Government export control warning"),
      HPND_export_US_acknowledgement => new String'("HPND with US Government export control warning and acknowledgment"),
      HPND_export_US_modify => new String'("HPND with US Government export control warning and modification rqmt"),
      HPND_export2_US => new String'("HPND with US Government export control and 2 disclaimers"),
      HPND_Fenneberg_Livingston => new String'("Historical Permission Notice and Disclaimer - Fenneberg-Livingston variant"),
      HPND_INRIA_IMAG => new String'("Historical Permission Notice and Disclaimer - INRIA-IMAG variant"),
      HPND_Intel => new String'("Historical Permission Notice and Disclaimer - Intel variant"),
      HPND_Kevlin_Henney => new String'("Historical Permission Notice and Disclaimer - Kevlin Henney variant"),
      HPND_Markus_Kuhn => new String'("Historical Permission Notice and Disclaimer - Markus Kuhn variant"),
      HPND_merchantability_variant => new String'("Historical Permission Notice and Disclaimer - merchantability variant"),
      HPND_MIT_disclaimer => new String'("Historical Permission Notice and Disclaimer with MIT disclaimer"),
      HPND_Pbmplus => new String'("Historical Permission Notice and Disclaimer - Pbmplus variant"),
      HPND_sell_MIT_disclaimer_xserver => new String'("Historical Permission Notice and Disclaimer - sell xserver variant with MIT disclaimer"),
      HPND_sell_regexpr => new String'("Historical Permission Notice and Disclaimer - sell regexpr variant"),
      HPND_sell_variant => new String'("Historical Permission Notice and Disclaimer - sell variant"),
      HPND_sell_variant_MIT_disclaimer => new String'("HPND sell variant with MIT disclaimer"),
      HPND_sell_variant_MIT_disclaimer_rev => new String'("HPND sell variant with MIT disclaimer - reverse"),
      Graphics_Gems => new String'("Graphics Gems License"),
      gtkbook => new String'("gtkbook License"),
      Gutmann => new String'("Gutmann License"),
      HaskellReport => new String'("Haskell Language Report License"),
      hdparm => new String'("hdparm License"),
      Hippocratic_2_1 => new String'("Hippocratic License 2.1"),
      HP_1986 => new String'("Hewlett-Packard 1986 License"),
      HP_1989 => new String'("Hewlett-Packard 1989 License"),
      HPND_UC => new String'("Historical Permission Notice and Disclaimer - University of California variant"),
      HPND_UC_export_US => new String'("Historical Permission Notice and Disclaimer - University of California, US export warning"),
      HTMLTIDY => new String'("HTML Tidy License"),
      IBM_pibs => new String'("IBM PowerPC Initialization and Boot Software"),
      ICU => new String'("ICU License"),
      IEC_Code_Components_EULA => new String'("IEC Code Components End-user licence agreement"),
      IJG => new String'("Independent JPEG Group License"),
      IJG_short => new String'("Independent JPEG Group License - short"),
      IPA => new String'("IPA Font License"),
      IPL_1_0 => new String'("IBM Public License v1.0"),
      ISC => new String'("ISC License"),
      ImageMagick => new String'("ImageMagick License"),
      Imlib2 => new String'("Imlib2 License"),
      Info_ZIP => new String'("Info-ZIP License"),
      Inner_Net_2_0 => new String'("Inner Net License v2.0"),
      Intel => new String'("Intel Open Source License"),
      Intel_ACPI => new String'("Intel ACPI Software License Agreement"),
      Interbase_1_0 => new String'("Interbase Public License v1.0"),
      ISC_Veillard => new String'("ISC Veillard variant"),
      Jam => new String'("Jam License"),
      JPL_image => new String'("JPL Image Use Policy"),
      JPNIC => new String'("Japan Network Information Center License"),
      JSON => new String'("JSON License"),
      JasPer_2_0 => new String'("JasPer License"),
      Kastrup => new String'("Kastrup License"),
      Kazlib => new String'("Kazlib License"),
      Knuth_CTAN => new String'("Knuth CTAN License"),
      LAL_1_2 => new String'("Licence Art Libre 1.2"),
      LAL_1_3 => new String'("Licence Art Libre 1.3"),
      LGPL_2_0_only => new String'("GNU Library General Public License v2 only"),
      LGPL_2_0_or_later => new String'("GNU Library General Public License v2 or later"),
      LGPL_2_1_only => new String'("GNU Lesser General Public License v2.1 only"),
      LGPL_2_1_or_later => new String'("GNU Lesser General Public License v2.1 or later"),
      LGPL_3_0_only => new String'("GNU Lesser General Public License v3.0 only"),
      LGPL_3_0_or_later => new String'("GNU Lesser General Public License v3.0 or later"),
      LGPLLR => new String'("Lesser General Public License For Linguistic Resources"),
      libutil_David_Nugent => new String'("libutil David Nugent License"),
      Id_LOOP => new String'("Common Lisp LOOP License"),
      LPD_document => new String'("LPD Documentation License"),
      LPL_1_0 => new String'("Lucent Public License Version 1.0"),
      LPL_1_02 => new String'("Lucent Public License v1.02"),
      LPPL_1_0 => new String'("LaTeX Project Public License v1.0"),
      LPPL_1_1 => new String'("LaTeX Project Public License v1.1"),
      LPPL_1_2 => new String'("LaTeX Project Public License v1.2"),
      LPPL_1_3a => new String'("LaTeX Project Public License v1.3a"),
      LPPL_1_3c => new String'("LaTeX Project Public License v1.3c"),
      Latex2e => new String'("Latex2e License"),
      Latex2e_translated_notice => new String'("Latex2e with translated notice permission"),
      Leptonica => new String'("Leptonica License"),
      LiLiQ_P_1_1 => new String'("Licence Libre du Qubec  Permissive version 1.1"),
      LiLiQ_R_1_1 => new String'("Licence Libre du Qubec  Rciprocit version 1.1"),
      LiLiQ_Rplus_1_1 => new String'("Licence Libre du Qubec  Rciprocit forte version 1.1"),
      Libpng => new String'("libpng License"),
      Linux_man_pages_1_para => new String'("Linux man-pages - 1 paragraph"),
      Linux_man_pages_copyleft => new String'("Linux man-pages Copyleft"),
      Linux_man_pages_copyleft_2_para => new String'("Linux man-pages Copyleft - 2 paragraphs"),
      Linux_man_pages_copyleft_var => new String'("Linux man-pages Copyleft Variant"),
      Linux_OpenIB => new String'("Linux Kernel Variant of OpenIB.org license"),
      lsof => new String'("lsof License"),
      Lucida_Bitmap_Fonts => new String'("Lucida Bitmap Fonts License"),
      LZMA_SDK_9_11_to_9_20 => new String'("LZMA SDK License (versions 9.11 to 9.20)"),
      LZMA_SDK_9_22 => new String'("LZMA SDK License (versions 9.22 and beyond)"),
      Mackerras_3_Clause => new String'("Mackerras 3-Clause License"),
      Mackerras_3_Clause_acknowledgment => new String'("Mackerras 3-Clause - acknowledgment variant"),
      magaz => new String'("magaz License"),
      mailprio => new String'("mailprio License"),
      Martin_Birgmeier => new String'("Martin Birgmeier License"),
      McPhee_slideshow => new String'("McPhee Slideshow License"),
      metamail => new String'("metamail License"),
      Minpack => new String'("Minpack License"),
      MIT => new String'("MIT License"),
      MIT_0 => new String'("MIT No Attribution"),
      MIT_CMU => new String'("CMU License"),
      MIT_advertising => new String'("Enlightenment License (e16)"),
      MIT_enna => new String'("enna License"),
      MIT_feh => new String'("feh License"),
      MIT_Festival => new String'("MIT Festival Variant"),
      MIT_Khronos_old => new String'("MIT Khronos - old variant"),
      MIT_Modern_Variant => new String'("MIT License Modern Variant"),
      MIT_open_group => new String'("MIT Open Group variant"),
      MIT_testregex => new String'("MIT testregex Variant"),
      MIT_Wu => new String'("MIT Tom Wu Variant"),
      MITNFA => new String'("MIT +no-false-attribs license"),
      MMIXware => new String'("MMIXware License"),
      MPEG_SSG => new String'("MPEG Software Simulation"),
      mpi_permissive => new String'("mpi Permissive License"),
      MPL_1_0 => new String'("Mozilla Public License 1.0"),
      MPL_1_1 => new String'("Mozilla Public License 1.1"),
      MPL_2_0 => new String'("Mozilla Public License 2.0"),
      MPL_2_0_no_copyleft_exception => new String'("Mozilla Public License 2.0 (no copyleft exception)"),
      mplus => new String'("mplus Font License"),
      MS_LPL => new String'("Microsoft Limited Public License"),
      MS_PL => new String'("Microsoft Public License"),
      MS_RL => new String'("Microsoft Reciprocal License"),
      MTLL => new String'("Matrix Template Library License"),
      MakeIndex => new String'("MakeIndex License"),
      MirOS => new String'("The MirOS Licence"),
      Motosoto => new String'("Motosoto License"),
      MulanPSL_1_0 => new String'("Mulan Permissive Software License, Version 1"),
      MulanPSL_2_0 => new String'("Mulan Permissive Software License, Version 2"),
      Multics => new String'("Multics License"),
      Mup => new String'("Mup License"),
      NAIST_2003 => new String'("Nara Institute of Science and Technology License (2003)"),
      NASA_1_3 => new String'("NASA Open Source Agreement 1.3"),
      NBPL_1_0 => new String'("Net Boolean Public License v1"),
      NCBI_PD => new String'("NCBI Public Domain Notice"),
      NCGL_UK_2_0 => new String'("Non-Commercial Government Licence"),
      NCL => new String'("NCL Source Code License"),
      NCSA => new String'("University of Illinois/NCSA Open Source License"),
      NGPL => new String'("Nethack General Public License"),
      NICTA_1_0 => new String'("NICTA Public Software License, Version 1.0"),
      NIST_PD => new String'("NIST Public Domain Notice"),
      NIST_PD_fallback => new String'("NIST Public Domain Notice with license fallback"),
      NLOD_1_0 => new String'("Norwegian Licence for Open Government Data (NLOD) 1.0"),
      NLOD_2_0 => new String'("Norwegian Licence for Open Government Data (NLOD) 2.0"),
      NIST_Software => new String'("NIST Software License"),
      NLPL => new String'("No Limit Public License"),
      NOSL => new String'("Netizen Open Source License"),
      NPL_1_0 => new String'("Netscape Public License v1.0"),
      NPL_1_1 => new String'("Netscape Public License v1.1"),
      NPOSL_3_0 => new String'("Non-Profit Open Software License 3.0"),
      NRL => new String'("NRL License"),
      NTP => new String'("NTP License"),
      NTP_0 => new String'("NTP No Attribution"),
      Naumen => new String'("Naumen Public License"),
      Net_SNMP => new String'("Net-SNMP License"),
      NetCDF => new String'("NetCDF license"),
      Newsletr => new String'("Newsletr License"),
      Nokia => new String'("Nokia Open Source License"),
      Noweb => new String'("Noweb License"),
      O_UDA_1_0 => new String'("Open Use of Data Agreement v1.0"),
      OAR => new String'("OAR License"),
      OCCT_PL => new String'("Open CASCADE Technology Public License"),
      OCLC_2_0 => new String'("OCLC Research Public License 2.0"),
      ODC_By_1_0 => new String'("Open Data Commons Attribution License v1.0"),
      ODbL_1_0 => new String'("Open Data Commons Open Database License v1.0"),
      OFFIS => new String'("OFFIS License"),
      OFL_1_0 => new String'("SIL Open Font License 1.0"),
      OFL_1_0_RFN => new String'("SIL Open Font License 1.0 with Reserved Font Name"),
      OFL_1_0_no_RFN => new String'("SIL Open Font License 1.0 with no Reserved Font Name"),
      OFL_1_1 => new String'("SIL Open Font License 1.1"),
      OFL_1_1_RFN => new String'("SIL Open Font License 1.1 with Reserved Font Name"),
      OFL_1_1_no_RFN => new String'("SIL Open Font License 1.1 with no Reserved Font Name"),
      OGC_1_0 => new String'("OGC Software License, Version 1.0"),
      OGDL_Taiwan_1_0 => new String'("Taiwan Open Government Data License, version 1.0"),
      OGL_Canada_2_0 => new String'("Open Government Licence - Canada"),
      OGL_UK_1_0 => new String'("Open Government Licence v1.0"),
      OGL_UK_2_0 => new String'("Open Government Licence v2.0"),
      OGL_UK_3_0 => new String'("Open Government Licence v3.0"),
      OGTSL => new String'("Open Group Test Suite License"),
      OLDAP_1_1 => new String'("Open LDAP Public License v1.1"),
      OLDAP_1_2 => new String'("Open LDAP Public License v1.2"),
      OLDAP_1_3 => new String'("Open LDAP Public License v1.3"),
      OLDAP_1_4 => new String'("Open LDAP Public License v1.4"),
      OLDAP_2_0 => new String'("Open LDAP Public License v2.0 (or possibly 2.0A and 2.0B)"),
      OLDAP_2_0_1 => new String'("Open LDAP Public License v2.0.1"),
      OLDAP_2_1 => new String'("Open LDAP Public License v2.1"),
      OLDAP_2_2 => new String'("Open LDAP Public License v2.2"),
      OLDAP_2_2_1 => new String'("Open LDAP Public License v2.2.1"),
      OLDAP_2_2_2 => new String'("Open LDAP Public License 2.2.2"),
      OLDAP_2_3 => new String'("Open LDAP Public License v2.3"),
      OLDAP_2_4 => new String'("Open LDAP Public License v2.4"),
      OLDAP_2_5 => new String'("Open LDAP Public License v2.5"),
      OLDAP_2_6 => new String'("Open LDAP Public License v2.6"),
      OLDAP_2_7 => new String'("Open LDAP Public License v2.7"),
      OLDAP_2_8 => new String'("Open LDAP Public License v2.8"),
      OLFL_1_3 => new String'("Open Logistics Foundation License Version 1.3"),
      OML => new String'("Open Market License"),
      OpenPBS_2_3 => new String'("OpenPBS v2.3 Software License"),
      OpenVision => new String'("OpenVision License"),
      OPL_1_0 => new String'("Open Public License v1.0"),
      OPL_UK_3_0 => new String'("United Kingdom Open Parliament Licence v3.0"),
      OPUBL_1_0 => new String'("Open Publication License v1.0"),
      OSET_PL_2_1 => new String'("OSET Public License version 2.1"),
      OSL_1_0 => new String'("Open Software License 1.0"),
      OSL_1_1 => new String'("Open Software License 1.1"),
      OSL_2_0 => new String'("Open Software License 2.0"),
      OSL_2_1 => new String'("Open Software License 2.1"),
      OSL_3_0 => new String'("Open Software License 3.0"),
      OpenSSL => new String'("OpenSSL License"),
      OpenSSL_standalone => new String'("OpenSSL License - standalone"),
      PADL => new String'("PADL License"),
      PDDL_1_0 => new String'("Open Data Commons Public Domain Dedication & License 1.0"),
      PHP_3_0 => new String'("PHP License v3.0"),
      PHP_3_01 => new String'("PHP License v3.01"),
      PSF_2_0 => new String'("Python Software Foundation License 2.0"),
      Parity_6_0_0 => new String'("The Parity Public License 6.0.0"),
      Parity_7_0_0 => new String'("The Parity Public License 7.0.0"),
      Pixar => new String'("Pixar License"),
      pkgconf => new String'("pkgconf License"),
      Plexus => new String'("Plexus Classworlds License"),
      pnmstitch => new String'("pnmstitch License"),
      PolyForm_Noncommercial_1_0_0 => new String'("PolyForm Noncommercial License 1.0.0"),
      PolyForm_Small_Business_1_0_0 => new String'("PolyForm Small Business License 1.0.0"),
      PostgreSQL => new String'("PostgreSQL License"),
      PPL => new String'("Peer Production License"),
      Python_2_0 => new String'("Python License 2.0"),
      Python_2_0_1 => new String'("Python License 2.0.1"),
      QPL_1_0 => new String'("Q Public License 1.0"),
      QPL_1_0_INRIA_2004 => new String'("Q Public License 1.0 - INRIA 2004 variant"),
      python_ldap => new String'("Python ldap License"),
      Qhull => new String'("Qhull License"),
      radvd => new String'("radvd License"),
      RHeCos_1_1 => new String'("Red Hat eCos Public License v1.1"),
      RPL_1_1 => new String'("Reciprocal Public License 1.1"),
      RPL_1_5 => new String'("Reciprocal Public License 1.5"),
      RPSL_1_0 => new String'("RealNetworks Public Source License v1.0"),
      RSA_MD => new String'("RSA Message-Digest License"),
      RSCPL => new String'("Ricoh Source Code Public License"),
      Rdisc => new String'("Rdisc License"),
      Ruby => new String'("Ruby License"),
      SAX_PD => new String'("Sax Public Domain Notice"),
      SAX_PD_2_0 => new String'("Sax Public Domain Notice 2.0"),
      SCEA => new String'("SCEA Shared Source License"),
      SchemeReport => new String'("Scheme Language Report License"),
      SGI_B_1_0 => new String'("SGI Free Software License B v1.0"),
      SGI_B_1_1 => new String'("SGI Free Software License B v1.1"),
      SGI_B_2_0 => new String'("SGI Free Software License B v2.0"),
      SGI_OpenGL => new String'("SGI OpenGL License"),
      SGP4 => new String'("SGP4 Permission Notice"),
      SHL_0_5 => new String'("Solderpad Hardware License v0.5"),
      SHL_0_51 => new String'("Solderpad Hardware License, Version 0.51"),
      SISSL => new String'("Sun Industry Standards Source License v1.1"),
      SISSL_1_2 => new String'("Sun Industry Standards Source License v1.2"),
      SL => new String'("SL License"),
      SMLNJ => new String'("Standard ML of New Jersey License"),
      SMPPL => new String'("Secure Messaging Protocol Public License"),
      SNIA => new String'("SNIA Public License 1.1"),
      snprintf => new String'("snprintf License"),
      softSurfer => new String'("softSurfer License"),
      Soundex => new String'("Soundex License"),
      SPL_1_0 => new String'("Sun Public License v1.0"),
      ssh_keyscan => new String'("ssh-keyscan License"),
      SSH_OpenSSH => new String'("SSH OpenSSH license"),
      SSH_short => new String'("SSH short notice"),
      SSLeay_standalone => new String'("SSLeay License - standalone"),
      SSPL_1_0 => new String'("Server Side Public License, v 1"),
      SWL => new String'("Scheme Widget Library (SWL) Software License Agreement"),
      Saxpath => new String'("Saxpath License"),
      Sendmail => new String'("Sendmail License"),
      Sendmail_8_23 => new String'("Sendmail License 8.23"),
      SimPL_2_0 => new String'("Simple Public License 2.0"),
      Sleepycat => new String'("Sleepycat License"),
      Spencer_86 => new String'("Spencer License 86"),
      Spencer_94 => new String'("Spencer License 94"),
      Spencer_99 => new String'("Spencer License 99"),
      SugarCRM_1_1_3 => new String'("SugarCRM Public License v1.1.3"),
      Sun_PPP => new String'("Sun PPP License"),
      Sun_PPP_2000 => new String'("Sun PPP License (2000)"),
      SunPro => new String'("SunPro License"),
      swrule => new String'("swrule License"),
      Symlinks => new String'("Symlinks License"),
      TAPR_OHL_1_0 => new String'("TAPR Open Hardware License v1.0"),
      TCL => new String'("TCL/TK License"),
      TCP_wrappers => new String'("TCP Wrappers License"),
      TermReadKey => new String'("TermReadKey License"),
      TGPPL_1_0 => new String'("Transitive Grace Period Public Licence 1.0"),
      threeparttable => new String'("threeparttable License"),
      TMate => new String'("TMate Open Source License"),
      TORQUE_1_1 => new String'("TORQUE v2.5+ Software License v1.1"),
      TOSL => new String'("Trusster Open Source License"),
      TPDL => new String'("Time::ParseDate License"),
      TPL_1_0 => new String'("THOR Public License 1.0"),
      TTWL => new String'("Text-Tabs+Wrap License"),
      TTYP0 => new String'("TTYP0 License"),
      TU_Berlin_1_0 => new String'("Technische Universitaet Berlin License 1.0"),
      TU_Berlin_2_0 => new String'("Technische Universitaet Berlin License 2.0"),
      UCAR => new String'("UCAR License"),
      UCL_1_0 => new String'("Upstream Compatibility License v1.0"),
      UPL_1_0 => new String'("Universal Permissive License v1.0"),
      ulem => new String'("ulem License"),
      UMich_Merit => new String'("Michigan/Merit Networks License"),
      Unicode_3_0 => new String'("Unicode License v3"),
      Unicode_DFS_2015 => new String'("Unicode License Agreement - Data Files and Software (2015)"),
      Unicode_DFS_2016 => new String'("Unicode License Agreement - Data Files and Software (2016)"),
      Unicode_TOU => new String'("Unicode Terms of Use"),
      UnixCrypt => new String'("UnixCrypt License"),
      Unlicense => new String'("The Unlicense"),
      URT_RLE => new String'("Utah Raster Toolkit Run Length Encoded License"),
      VOSTROM => new String'("VOSTROM Public License for Open Source"),
      VSL_1_0 => new String'("Vovida Software License v1.0"),
      Vim => new String'("Vim License"),
      W3C => new String'("W3C Software Notice and License (2002-12-31)"),
      W3C_19980720 => new String'("W3C Software Notice and License (1998-07-20)"),
      W3C_20150513 => new String'("W3C Software Notice and Document License (2015-05-13)"),
      WTFPL => new String'("Do What The F*ck You Want To Public License"),
      w3m => new String'("w3m License"),
      Watcom_1_0 => new String'("Sybase Open Watcom Public License 1.0"),
      Widget_Workshop => new String'("Widget Workshop License"),
      Wsuipa => new String'("Wsuipa License"),
      X11 => new String'("X11 License"),
      X11_distribute_modifications_variant => new String'("X11 License Distribution Modification Variant"),
      XFree86_1_1 => new String'("XFree86 License 1.1"),
      XSkat => new String'("XSkat License"),
      Xdebug_1_03 => new String'("Xdebug License v 1.03"),
      Xerox => new String'("Xerox License"),
      Xfig => new String'("Xfig License"),
      xkeyboard_config_Zinoviev => new String'("xkeyboard-config Zinoviev License"),
      xlock => new String'("xlock License"),
      Xnet => new String'("X.Net License"),
      xzoom => new String'("xzoom License"),
      YPL_1_0 => new String'("Yahoo! Public License v1.0"),
      YPL_1_1 => new String'("Yahoo! Public License v1.1"),
      ZPL_1_1 => new String'("Zope Public License 1.1"),
      ZPL_2_0 => new String'("Zope Public License 2.0"),
      ZPL_2_1 => new String'("Zope Public License 2.1"),
      Zed => new String'("Zed License"),
      Zeeff => new String'("Zeeff License"),
      Zend_2_0 => new String'("Zend License v2.0"),
      Zimbra_1_3 => new String'("Zimbra Public License v1.3"),
      Zimbra_1_4 => new String'("Zimbra Public License v1.4"),
      Zlib => new String'("zlib License"),
      blessing => new String'("SQLite Blessing"),
      bzip2_1_0_5 => new String'("bzip2 and libbzip2 License v1.0.5"),
      bzip2_1_0_6 => new String'("bzip2 and libbzip2 License v1.0.6"),
      copyleft_next_0_3_0 => new String'("copyleft-next 0.3.0"),
      copyleft_next_0_3_1 => new String'("copyleft-next 0.3.1"),
      curl => new String'("curl License"),
      diffmark => new String'("diffmark license"),
      dvipdfm => new String'("dvipdfm License"),
      eGenix => new String'("eGenix.com Public License 1.1.0"),
      etalab_2_0 => new String'("Etalab Open License 2.0"),
      gSOAP_1_3b => new String'("gSOAP Public License v1.3b"),
      gnuplot => new String'("gnuplot License"),
      iMatix => new String'("iMatix Standard Function Library Agreement"),
      libpng_2_0 => new String'("PNG Reference Library version 2"),
      libselinux_1_0 => new String'("libselinux public domain notice"),
      libtiff => new String'("libtiff License"),
      mpich2 => new String'("mpich2 License"),
      psfrag => new String'("psfrag License"),
      psutils => new String'("psutils License"),
      xinetd => new String'("xinetd License"),
      xpp => new String'("XPP License"),
      zlib_acknowledgement => new String'("zlib/libpng License with Acknowledgement"));

   function Name (I : Id) return String
   is (Name_Ptr (I).all);

   function Valid_Id (Str : String) return Boolean;
   function From_Id (Str : String) return Id;

end SPDX.Licenses;
